import{useEffect,useState}from"react";import{cmsSupabase}from"./supabase";import type{CmsRole}from"./cmsGovernance";
type Snapshot={id:string;provider:'ga4'|'gsc';period_start:string;period_end:string;metrics:Record<string,number>;dimensions:Record<string,Array<Record<string,string|number>>>;source_updated_at:string;fetched_at:string};
type Inquiry={total_28d:number;previous_28d:number;new:number;contacted:number;qualified:number;closed:number;source_updated_at:string|null};
const n=(value:number|undefined)=>value===undefined?'—':new Intl.NumberFormat('zh-CN').format(value),pct=(value:number|undefined)=>value===undefined?'—':`${(value*100).toFixed(1)}%`;
export default function AnalyticsDashboard({role}:{role:CmsRole}){const[ga,setGa]=useState<Snapshot|null>(null),[gsc,setGsc]=useState<Snapshot|null>(null),[inquiry,setInquiry]=useState<Inquiry|null>(null),[syncs,setSyncs]=useState<Array<{id:string;status:string;requested_at:string;completed_at:string|null;error_message:string|null}>>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const allowed=['super_admin','seo','reviewer','sales'].includes(role),canSync=['super_admin','seo'].includes(role);
 const load=async()=>{if(!cmsSupabase||!allowed)return;const[{data:s,error},{data:y},{data:q,error:qe}]=await Promise.all([cmsSupabase.from('cms_analytics_snapshots').select('*').order('fetched_at',{ascending:false}).limit(20),cmsSupabase.from('cms_analytics_syncs').select('id,status,requested_at,completed_at,error_message').order('requested_at',{ascending:false}).limit(10),cmsSupabase.rpc('cms_inquiry_dashboard')]);const rows=(s??[])as Snapshot[];setGa(rows.find(x=>x.provider==='ga4')??null);setGsc(rows.find(x=>x.provider==='gsc')??null);setSyncs(y??[]);setInquiry(q as Inquiry|null);setNotice(error?.message??(qe&&role!=='seo'?qe.message:''))};useEffect(()=>{void load()},[role]);
 const sync=async()=>{if(!cmsSupabase)return;setBusy(true);const{data,error}=await cmsSupabase.rpc('cms_request_analytics_sync');if(error){setBusy(false);return setNotice(error.message)}const task=Array.isArray(data)?data[0]:data,endpoint=(import.meta.env.VITE_CMS_ANALYTICS_API_URL as string|undefined)||"https://cms.wonlyglobal.com/api/analytics";if(!endpoint){setBusy(false);setNotice('同步任务已登记，但自有分析服务接口尚未配置；当前数据不会被伪造或覆盖');await load();return}try{const token=(await cmsSupabase.auth.getSession()).data.session?.access_token;const response=await fetch(`${endpoint.replace(/\/$/,'')}/analytics/sync`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({sync_id:task.id})});if(!response.ok)throw new Error(`分析服务返回 ${response.status}`);setNotice('同步已触发，指标以服务器完成回执为准')}catch(error){setNotice(error instanceof Error?error.message:'同步失败')}finally{setBusy(false);await load()}};
 if(!allowed)return <div className="cms-card cms-module-empty"><h2>无权查看数据看板</h2><p>仅超级管理员、SEO、审核发布和销售角色可以访问。</p></div>;
 const card=(label:string,value:string,detail:string)=><div className="cms-card cms-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;
 return <div className="cms-analytics"><header className="cms-card cms-analytics-head"><div><h2>真实数据看板</h2><p>GA4 / GSC 为服务器只读同步快照；询盘统计直接来自 CMS。无快照时显示“未连接”，不会生成估算值。</p></div><button className="cms-button" disabled={!canSync||busy} onClick={()=>void sync()}>{busy?'同步中…':'同步 GA4 / GSC'}</button></header>{notice?<p className={notice.includes('已')?'cms-success':'cms-error'}>{notice}</p>:null}<section><h3>GA4 · 最近28天</h3>{ga?<div className="cms-metric-grid">{card('会话',n(ga.metrics.sessions),`数据截至 ${ga.period_end}`)}{card('用户',n(ga.metrics.users),'GA4 Data API')}{card('自然搜索会话',n(ga.metrics.organic_sessions),'Organic Search')}{card('询盘转化',n(ga.metrics.generate_lead),'generate_lead 事件')}{card('参与率',pct(ga.metrics.engagement_rate),'真实聚合值')}</div>:<div className="cms-card cms-data-missing"><strong>GA4 未连接或尚无成功快照</strong><span>配置服务账号、Property ID 与自有分析服务后再同步。</span></div>}</section><section><h3>Google Search Console · 延迟3天的最近28天</h3>{gsc?<div className="cms-metric-grid">{card('点击',n(gsc.metrics.clicks),`数据截至 ${gsc.period_end}`)}{card('展示',n(gsc.metrics.impressions),'Search Analytics API')}{card('CTR',pct(gsc.metrics.ctr),'点击 ÷ 展示')}{card('平均排名',gsc.metrics.position?.toFixed(1)??'—','按展示加权')}</div>:<div className="cms-card cms-data-missing"><strong>GSC 未连接或尚无成功快照</strong><span>授权 sc-domain:wonlyglobal.com 后再同步。</span></div>}</section><section><h3>网站询盘 · CMS 实时</h3>{inquiry?<div className="cms-metric-grid">{card('近28天',n(inquiry.total_28d),`更新 ${inquiry.source_updated_at?new Date(inquiry.source_updated_at).toLocaleString('zh-CN'):'暂无询盘'}`)}{card('新询盘',n(inquiry.new),'当前状态')}{card('已联系',n(inquiry.contacted),'当前状态')}{card('有效商机',n(inquiry.qualified),'当前状态')}{card('已关闭',n(inquiry.closed),'当前状态')}</div>:<div className="cms-card cms-data-missing"><strong>当前角色无询盘统计权限或数据不可用</strong></div>}</section><section className="cms-card cms-sync-history"><h3>同步证据</h3>{syncs.map(item=><article key={item.id}><span>{new Date(item.requested_at).toLocaleString('zh-CN')}</span><strong>{item.status}</strong><small>{item.error_message||item.completed_at&&`完成 ${new Date(item.completed_at).toLocaleString('zh-CN')}`||'等待服务端回执'}</small></article>)}{!syncs.length?<p className="cms-muted">尚无同步记录。</p>:null}</section></div>}
