import { useEffect, useMemo, useRef, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { ARTICLES, type Article, type ArticleBlock, type ArticleCategory } from "@/lib/articles";
import { cmsSupabase } from "./supabase";

type ArticleRow = { id:string;page_key:string;status:"draft"|"published";draft_content:Partial<Article>|null;published_content:Partial<Article>|null;updated_at:string;published_at:string|null };
const CATEGORIES:ArticleCategory[]=["Buying Guide","Technology","Market Insight","Company"];
const keyFor=(slug:string)=>`article:${slug}`;
const blocksToText=(blocks:ArticleBlock[])=>blocks.map(block=>block.type==="h2"?`## ${block.text}`:block.type==="ul"?block.items.map(item=>`- ${item}`).join("\n"):block.text).join("\n\n");
const textToBlocks=(value:string):ArticleBlock[]=>{const blocks:ArticleBlock[]=[];let list:string[]=[];const flush=()=>{if(list.length)blocks.push({type:"ul",items:list});list=[]};value.split(/\r?\n/).forEach(raw=>{const line=raw.trim();if(!line){flush();return}if(/^##\s+/.test(line)){flush();blocks.push({type:"h2",text:line.replace(/^##\s+/,"")});return}if(/^[-*]\s+/.test(line)){list.push(line.replace(/^[-*]\s+/,""));return}flush();blocks.push({type:"p",text:line})});flush();return blocks};
const merge=(base:Article,override?:Partial<Article>|null):Article=>({...base,...(override??{}),slug:base.slug});

export default function ArticleManager({session}:{session:Session}){
 const[rows,setRows]=useState<ArticleRow[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState<ArticleCategory|"All">("All"),[selected,setSelected]=useState<Article|null>(null),[draft,setDraft]=useState<Article|null>(null),[body,setBody]=useState(""),[keywords,setKeywords]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const coverInput=useRef<HTMLInputElement>(null);
 const load=async()=>{if(!cmsSupabase)return;const{data,error}=await cmsSupabase.from("cms_pages").select("id,page_key,status,draft_content,published_content,updated_at,published_at").like("page_key","article:%").order("updated_at",{ascending:false});if(error)setNotice(error.message);else setRows((data??[]) as ArticleRow[])};
 useEffect(()=>{void load()},[]);
 const rowMap=useMemo(()=>new Map(rows.map(row=>[row.page_key,row])),[rows]);
 const articles=useMemo(()=>ARTICLES.filter(article=>{const needle=query.trim().toLowerCase();return(category==="All"||article.category===category)&&(!needle||[article.title,article.slug,article.category,article.keywords.join(" ")].join(" ").toLowerCase().includes(needle))}),[category,query]);
 const open=(article:Article)=>{const row=rowMap.get(keyFor(article.slug)),next=merge(article,row?.draft_content??row?.published_content);setSelected(article);setDraft(next);setBody(blocksToText(next.body));setKeywords(next.keywords.join("\n"));setNotice("")};
 const change=<K extends keyof Article>(key:K,value:Article[K])=>setDraft(current=>current?{...current,[key]:value}:current);
 const currentContent=():Article|null=>draft?{...draft,body:textToBlocks(body),keywords:keywords.split(/[\n,]/).map(item=>item.trim()).filter(Boolean)}:null;
 const persist=async(publish:boolean)=>{const next=currentContent();if(!cmsSupabase||!selected||!next)return;setBusy(true);setNotice("");const existing=rowMap.get(keyFor(selected.slug));const payload={page_key:keyFor(selected.slug),page_type:"article",route:`/insights/${selected.slug}`,title:next.title,source_locale:"en",draft_content:next,translations:{},status:publish?"published":(existing?.status??"draft"),updated_by:session.user.id,...(publish?{published_content:next,published_at:new Date().toISOString()}:{})};const{data,error}=await cmsSupabase.from("cms_pages").upsert(payload,{onConflict:"page_key"}).select("id").single();if(error){setNotice(error.message);setBusy(false);return}await cmsSupabase.from("cms_revisions").insert({page_id:data.id,action:publish?"published":"draft_saved",snapshot:next,created_by:session.user.id});setNotice(publish?"文章已发布，线上文章将读取这个版本。":"文章草稿已保存，线上内容没有变化。");await load();setBusy(false)};
 const upload=async(file:File)=>{if(!cmsSupabase||!selected)return;if(file.size>10*1024*1024){setNotice("图片不能超过 10MB");return}setBusy(true);const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"),path=`articles/${selected.slug}/${Date.now()}-${safe}`;const{error}=await cmsSupabase.storage.from("website-assets").upload(path,file);if(error){setNotice(error.message);setBusy(false);return}const{data}=cmsSupabase.storage.from("website-assets").getPublicUrl(path);await cmsSupabase.from("cms_assets").insert({storage_path:path,public_url:data.publicUrl,original_name:file.name,mime_type:file.type,byte_size:file.size,uploaded_by:session.user.id});change("cover",data.publicUrl);setNotice("封面已上传，请保存草稿或确认发布。");setBusy(false)};

 if(selected&&draft)return <div className="cms-article-editor"><div className="cms-article-editor-head"><div><button className="cms-link-button" onClick={()=>{setSelected(null);setDraft(null)}}>← 返回全部文章</button><h2>{draft.title}</h2><small>/insights/{draft.slug}</small></div><div><a className="cms-button secondary" href={`/insights/${draft.slug}`} target="_blank" rel="noreferrer">查看线上文章</a><button className="cms-button secondary" disabled={busy} onClick={()=>void persist(false)}>保存草稿</button><button className="cms-button" disabled={busy} onClick={()=>void persist(true)}>确认并发布</button></div></div>{notice?<p className={notice.includes("已")?"cms-success":"cms-error"}>{notice}</p>:null}<div className="cms-article-form cms-card">
  <label className="cms-field"><span>文章标题</span><input value={draft.title} onChange={e=>change("title",e.target.value)}/></label><div className="cms-article-two"><label className="cms-field"><span>分类</span><select value={draft.category} onChange={e=>change("category",e.target.value as ArticleCategory)}>{CATEGORIES.map(item=><option key={item}>{item}</option>)}</select></label><label className="cms-field"><span>发布日期</span><input type="date" value={draft.date} onChange={e=>change("date",e.target.value)}/></label></div>
  <label className="cms-field"><span>摘要</span><textarea value={draft.excerpt} onChange={e=>change("excerpt",e.target.value)}/></label><label className="cms-field"><span>SEO 标题</span><input value={draft.seoTitle} onChange={e=>change("seoTitle",e.target.value)}/></label><label className="cms-field"><span>SEO 描述</span><textarea value={draft.description} onChange={e=>change("description",e.target.value)}/></label><label className="cms-field"><span>SEO 关键词（每行一个，也可逗号分隔）</span><textarea value={keywords} onChange={e=>setKeywords(e.target.value)}/></label>
  <label className="cms-field"><span>封面图片地址</span><input value={draft.cover} onChange={e=>change("cover",e.target.value)}/></label><input ref={coverInput} style={{display:"none"}} type="file" accept="image/jpeg,image/png,image/webp,image/avif" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/>{draft.cover?<div style={{position:"relative",width:"min(520px, 100%)",cursor:"pointer"}} onClick={()=>coverInput.current?.click()}><img className="cms-article-cover" style={{width:"100%",outline:"3px solid #2864ff",outlineOffset:3}} src={draft.cover} alt="文章封面预览"/><button type="button" disabled={busy} style={{position:"absolute",right:12,top:12,border:0,borderRadius:8,background:"#1e5eff",color:"#fff",padding:"9px 13px",fontWeight:650,boxShadow:"0 6px 18px rgba(23,32,51,.28)",cursor:"pointer"}} onClick={event=>{event.stopPropagation();coverInput.current?.click()}}>替换图片</button></div>:<button type="button" className="cms-button secondary" onClick={()=>coverInput.current?.click()}>上传封面图片</button>}
  <label className="cms-field"><span>文章正文</span><small>二级标题用“## 标题”，列表用“- 内容”；普通段落直接输入。</small><textarea className="cms-article-body" value={body} onChange={e=>setBody(e.target.value)}/></label>
 </div></div>;
 return <><div className="cms-module-callout"><strong>官网文章库</strong><span>已自动读取官网当前 {ARTICLES.length} 篇英文文章；可编辑文案、封面与 SEO。保存草稿不影响线上，确认发布后才更新。</span></div><div className="cms-article-filters"><input aria-label="搜索文章" placeholder="搜索标题、网址或关键词" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="文章分类" value={category} onChange={e=>setCategory(e.target.value as ArticleCategory|"All")}><option value="All">全部分类</option>{CATEGORIES.map(item=><option key={item}>{item}</option>)}</select><span>显示 {articles.length} / {ARTICLES.length} 篇</span></div><div className="cms-table-wrap"><table className="cms-table"><thead><tr><th>文章</th><th>分类</th><th>发布日期</th><th>状态</th><th/></tr></thead><tbody>{articles.map(article=>{const row=rowMap.get(keyFor(article.slug));return <tr key={article.slug}><td><strong>{article.title}</strong><small>/insights/{article.slug}</small></td><td>{article.category}</td><td>{article.dateLabel||article.date}</td><td><span className={`cms-state ${row?.status==="published"||!row?"published":"draft"}`}>{row?.status==="published"?"后台已发布":row?"有草稿":"官网已发布"}</span></td><td><button onClick={()=>open(article)}>编辑文章</button></td></tr>})}</tbody></table></div></>;
}
