import{useCallback,useEffect,useMemo,useState}from"react";
import{cmsSupabase}from"./supabase";
import type{CmsRole}from"./cmsGovernance";
type Row={id:string;actor_id:string|null;actor_email:string|null;action:string;resource_type:string;resource_id:string|null;metadata:Record<string,unknown>;created_at:string;total_count:number};
const PAGE=50;
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;
export default function AuditCenter({role}:{role:CmsRole}){
 const[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[action,setAction]=useState(""),[resource,setResource]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(0),[selected,setSelected]=useState<Row|null>(null),[notice,setNotice]=useState("");const allowed=role==="super_admin"||role==="reviewer";
 const load=useCallback(async()=>{if(!cmsSupabase||!allowed)return;const{data,error}=await cmsSupabase.rpc("cms_list_audit_logs",{p_query:query||null,p_action:action||null,p_resource_type:resource||null,p_from:from?new Date(`${from}T00:00:00`).toISOString():null,p_to:to?new Date(`${to}T23:59:59.999`).toISOString():null,p_limit:PAGE,p_offset:page*PAGE});setNotice(error?error.message:"");setRows((data??[])as Row[])},[allowed,query,action,resource,from,to,page]);useEffect(()=>{void load()},[load]);
 const actions=useMemo(()=>[...new Set(rows.map(row=>row.action))].sort(),[rows]),resources=useMemo(()=>[...new Set(rows.map(row=>row.resource_type))].sort(),[rows]),total=Number(rows[0]?.total_count??0);
 const exportCsv=()=>{const lines=[["time","actor","action","resource_type","resource_id","metadata"].map(csvCell).join(","),...rows.map(row=>[row.created_at,row.actor_email||row.actor_id,row.action,row.resource_type,row.resource_id,JSON.stringify(row.metadata)].map(csvCell).join(","))];const blob=new Blob(["\uFEFF"+lines.join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`wonly-cms-audit-${new Date().toISOString().slice(0,10)}-page-${page+1}.csv`;link.click();URL.revokeObjectURL(url)};
 if(!allowed)return <div className="cms-card cms-module-empty"><h2>无权查看审计日志</h2><p>仅超级管理员和审核发布角色可以访问审计中心。</p></div>;
 return <div className="cms-audit-layout"><section className="cms-card cms-audit-toolbar"><label><span>关键词</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="邮箱、资源ID或元数据"/></label><label><span>动作</span><select value={action} onChange={e=>{setAction(e.target.value);setPage(0)}}><option value="">全部</option>{actions.map(item=><option key={item}>{item}</option>)}</select></label><label><span>资源</span><select value={resource} onChange={e=>{setResource(e.target.value);setPage(0)}}><option value="">全部</option>{resources.map(item=><option key={item}>{item}</option>)}</select></label><label><span>开始日期</span><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(0)}}/></label><label><span>结束日期</span><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(0)}}/></label><button className="cms-button secondary" disabled={!rows.length} onClick={exportCsv}>导出本页 CSV</button></section>{notice?<p className="cms-error">{notice}</p>:null}<section className="cms-table-wrap"><table className="cms-table"><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>ID</th><th/></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString("zh-CN")}</td><td>{row.actor_email||row.actor_id||"系统"}</td><td>{row.action}</td><td>{row.resource_type}</td><td><code>{row.resource_id||"—"}</code></td><td><button onClick={()=>setSelected(row)}>详情</button></td></tr>)}</tbody></table>{!rows.length?<p className="cms-module-empty">当前筛选条件下暂无审计记录。</p>:null}</section><nav className="cms-audit-pagination"><span>共 {total} 条 · 第 {page+1} 页</span><button disabled={page===0} onClick={()=>setPage(value=>value-1)}>上一页</button><button disabled={(page+1)*PAGE>=total} onClick={()=>setPage(value=>value+1)}>下一页</button></nav>{selected?<aside className="cms-card cms-audit-detail"><header><div><h2>审计详情</h2><p>{selected.action} · {new Date(selected.created_at).toLocaleString("zh-CN")}</p></div><button onClick={()=>setSelected(null)}>关闭</button></header><dl><dt>操作者</dt><dd>{selected.actor_email||selected.actor_id||"系统"}</dd><dt>资源</dt><dd>{selected.resource_type} / {selected.resource_id||"—"}</dd></dl><pre>{JSON.stringify(selected.metadata,null,2)}</pre></aside>:null}</div>
}
