import{useEffect,useMemo,useState}from"react";
import{cmsSupabase}from"./supabase";
import{can,type CmsRole}from"./cmsGovernance";
import"./BulkSeoManager.css";
type Seo={title:string;description:string;canonical:string;robots:string;ogImage:string};
type Page={id:string;title:string;route:string;page_type:string;content_version:number;draft_content:Record<string,unknown>};
const empty:Seo={title:"",description:"",canonical:"",robots:"index,follow",ogImage:""};
const seoOf=(page:Page):Seo=>({...empty,...((page.draft_content?.seo??{})as Partial<Seo>)});
export default function BulkSeoManager({role}:{role:CmsRole}){
 const[pages,setPages]=useState<Page[]>([]),[drafts,setDrafts]=useState<Record<string,Seo>>({}),[selected,setSelected]=useState<Record<string,boolean>>({}),[query,setQuery]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const editable=can(role,"editSeo");
 const load=async()=>{if(!cmsSupabase)return;const{data,error}=await cmsSupabase.from("cms_pages").select("id,title,route,page_type,content_version,draft_content").order("route");const list=(data??[])as Page[];setPages(list);setDrafts(Object.fromEntries(list.map(p=>[p.id,seoOf(p)])));setNotice(error?.message??"")};useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>pages.filter(p=>`${p.title} ${p.route} ${p.page_type}`.toLowerCase().includes(query.toLowerCase())),[pages,query]);
 const change=(id:string,key:keyof Seo,value:string)=>setDrafts(current=>({...current,[id]:{...current[id],[key]:value}}));
 const save=async()=>{if(!cmsSupabase)return;const chosen=pages.filter(p=>selected[p.id]);if(!chosen.length)return setNotice("请至少选择一个页面");const invalid=chosen.find(p=>(drafts[p.id]?.title.length??0)>70||(drafts[p.id]?.description.length??0)>180);if(invalid)return setNotice(`${invalid.title} 的标题或描述超过限制`);setBusy(true);const updates=chosen.map(p=>({page_id:p.id,expected_version:p.content_version,seo:drafts[p.id]}));const{data,error}=await cmsSupabase.rpc("cms_bulk_update_seo",{p_updates:updates});setBusy(false);if(error)return setNotice(error.message);setNotice(`已更新 ${(data as {updated?:number}|null)?.updated??chosen.length} 个页面草稿；尚未发布`);setSelected({});await load()};
 const allVisible=visible.length>0&&visible.every(p=>selected[p.id]);
 return <div className="cms-bulk-seo"><section className="cms-card cms-seo-toolbar"><div><h2>批量 SEO</h2><p>只写入草稿；旧审批和待发布排期会自动失效。</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索页面、路径或类型"/><button className="cms-button secondary" onClick={()=>setSelected(current=>({...current,...Object.fromEntries(visible.map(p=>[p.id,!allVisible]))}))}>{allVisible?"取消当前页":"选择当前页"}</button><button className="cms-button" disabled={!editable||busy||!Object.values(selected).some(Boolean)} onClick={()=>void save()}>{busy?"保存中…":`保存选中 (${Object.values(selected).filter(Boolean).length})`}</button></section>{notice?<div className={notice.includes("已更新")?"cms-success":"cms-error"}>{notice}</div>:null}<div className="cms-seo-list">{visible.map(page=>{const seo=drafts[page.id]??empty;return <article className={`cms-card cms-seo-row ${selected[page.id]?"selected":""}`} key={page.id}><label className="cms-seo-check"><input type="checkbox" checked={!!selected[page.id]} onChange={e=>setSelected(s=>({...s,[page.id]:e.target.checked}))}/><span><strong>{page.title}</strong><small>{page.route} · {page.page_type} · v{page.content_version}</small></span></label><label><span>SEO 标题 <em>{seo.title.length}/70</em></span><input value={seo.title} onChange={e=>change(page.id,"title",e.target.value)}/></label><label className="wide"><span>描述 <em>{seo.description.length}/180</em></span><textarea value={seo.description} onChange={e=>change(page.id,"description",e.target.value)}/></label><label><span>Canonical</span><input value={seo.canonical} onChange={e=>change(page.id,"canonical",e.target.value)} placeholder={page.route}/></label><label><span>Robots</span><select value={seo.robots} onChange={e=>change(page.id,"robots",e.target.value)}><option>index,follow</option><option>noindex,follow</option><option>noindex,nofollow</option></select></label><label className="wide"><span>分享图 URL</span><input value={seo.ogImage} onChange={e=>change(page.id,"ogImage",e.target.value)}/></label></article>})}</div>{!editable?<p className="cms-error">当前角色只能查看 SEO；编辑者、SEO 或超级管理员可保存。</p>:null}</div>;
}
