import { useCallback, useEffect, useMemo, useState } from "react";
import { cmsSupabase } from "./supabase";

type Status = "new" | "contacted" | "qualified" | "closed";
type Inquiry = { id:string; created_at:string; status:Status; subject:string; name:string; company:string; job_title:string; country:string; email:string; phone:string; business_type:string; message:string; language:string; source:string; admin_notes:string };
const labels:Record<Status,string>={new:"新询盘",contacted:"已联系",qualified:"有效商机",closed:"已关闭"};

export default function InquiryDashboard({onBack,onSignOut}:{onBack:()=>void;onSignOut:()=>void}){
  const[rows,setRows]=useState<Inquiry[]>([]),[selected,setSelected]=useState<Inquiry|null>(null),[filter,setFilter]=useState<"all"|Status>("all"),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{if(!cmsSupabase)return;setLoading(true);const{data,error}=await cmsSupabase.from("cms_inquiries").select("*").order("created_at",{ascending:false}).limit(500);if(error)setNotice(error.message);else setRows((data??[]) as Inquiry[]);setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>filter==="all"?rows:rows.filter(row=>row.status===filter),[filter,rows]);
  const update=async(changes:Partial<Pick<Inquiry,"status"|"admin_notes">>)=>{if(!cmsSupabase||!selected)return;const{data,error}=await cmsSupabase.from("cms_inquiries").update({...changes,updated_at:new Date().toISOString()}).eq("id",selected.id).select().single();if(error)return setNotice(error.message);const next=data as Inquiry;setRows(current=>current.map(row=>row.id===next.id?next:row));setSelected(next);setNotice("询盘状态已保存")};
  return <main className="cms-root cms-inquiries"><header className="cms-visual-toolbar"><div className="cms-visual-brand"><strong>WONLY</strong><span>询盘管理</span></div><button className="cms-button secondary" onClick={onBack}>返回页面编辑</button><div className="cms-visual-actions"><button className="cms-button secondary" onClick={()=>void load()}>刷新</button><button className="cms-button secondary" onClick={onSignOut}>退出</button></div></header><section className="cms-inquiry-content"><div className="cms-inquiry-heading"><div><h1>网站询盘</h1><p>客户提交后直接保存在这里，邮件仅作为提醒。</p></div><div className="cms-inquiry-stats"><strong>{rows.filter(row=>row.status==="new").length}</strong><span>待处理</span><strong>{rows.length}</strong><span>全部</span></div></div>{notice?<p className="cms-visual-status">{notice}</p>:null}<div className="cms-inquiry-filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>全部</button>{(Object.keys(labels) as Status[]).map(status=><button key={status} className={filter===status?"active":""} onClick={()=>setFilter(status)}>{labels[status]}</button>)}</div><div className="cms-inquiry-layout"><div className="cms-inquiry-list">{loading?<p>正在加载…</p>:visible.length===0?<p className="cms-muted">暂无询盘</p>:visible.map(row=><button key={row.id} className={`cms-inquiry-row ${selected?.id===row.id?"active":""}`} onClick={()=>setSelected(row)}><span className={`cms-inquiry-badge ${row.status}`}>{labels[row.status]}</span><strong>{row.name}{row.company?` · ${row.company}`:""}</strong><span>{row.email}</span><span>{row.business_type||row.subject}</span><time>{new Date(row.created_at).toLocaleString("zh-CN")}</time></button>)}</div><aside className="cms-card cms-inquiry-detail">{selected?<><div className="cms-inquiry-detail-head"><div><span className={`cms-inquiry-badge ${selected.status}`}>{labels[selected.status]}</span><h2>{selected.name}</h2><p>{selected.company}{selected.job_title?` · ${selected.job_title}`:""}</p></div><select value={selected.status} onChange={event=>void update({status:event.target.value as Status})}>{(Object.keys(labels) as Status[]).map(status=><option key={status} value={status}>{labels[status]}</option>)}</select></div><dl><dt>邮箱</dt><dd><a href={`mailto:${selected.email}`}>{selected.email}</a></dd><dt>电话</dt><dd>{selected.phone||"—"}</dd><dt>国家/地区</dt><dd>{selected.country||"—"}</dd><dt>业务类型</dt><dd>{selected.business_type||"—"}</dd><dt>来源</dt><dd>{selected.source} · {selected.language.toUpperCase()}</dd><dt>提交时间</dt><dd>{new Date(selected.created_at).toLocaleString("zh-CN")}</dd></dl><section className="cms-inquiry-message"><strong>客户留言</strong><p>{selected.message}</p></section><label className="cms-field"><span>跟进备注</span><textarea defaultValue={selected.admin_notes} key={selected.id} onBlur={event=>void update({admin_notes:event.target.value})}/></label></>:<div className="cms-inquiry-empty">选择一条询盘查看完整内容</div>}</aside></div></section></main>
}
