import{useCallback,useEffect,useState}from"react";
import{cmsSupabase}from"./supabase";
import{can,type CmsRole}from"./cmsGovernance";
import"./PageTemplateLibrary.css";
type Page={id:string;title:string;page_type:string;content_version:number;route:string};
type Template={id:string;name:string;description:string;page_type:string;is_active:boolean;updated_at:string;source_page_id:string|null};
export default function PageTemplateLibrary({role}:{role:CmsRole}){
 const[pages,setPages]=useState<Page[]>([]),[templates,setTemplates]=useState<Template[]>([]),[source,setSource]=useState(""),[target,setTarget]=useState(""),[selected,setSelected]=useState(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const editable=can(role,"edit");
 const load=useCallback(async()=>{if(!cmsSupabase)return;const[{data:p,error:pe},{data:t,error:te}]=await Promise.all([cmsSupabase.from("cms_pages").select("id,title,page_type,content_version,route").order("title"),cmsSupabase.from("cms_page_templates").select("id,name,description,page_type,is_active,updated_at,source_page_id").order("updated_at",{ascending:false})]);setPages((p??[])as Page[]);setTemplates((t??[])as Template[]);setSource(v=>v||String(p?.[0]?.id??""));setTarget(v=>v||String(p?.[0]?.id??""));setSelected(v=>v||String(t?.[0]?.id??""));setNotice(pe?.message??te?.message??"")},[]);useEffect(()=>{void load()},[load]);
 const create=async()=>{if(!cmsSupabase||!source)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_create_template",{p_page_id:source,p_name:name,p_description:description});setBusy(false);if(error)return setNotice(error.message);setName("");setDescription("");setNotice("模板已创建");await load()};
 const apply=async()=>{if(!cmsSupabase||!selected||!target)return;const page=pages.find(p=>p.id===target);if(!page)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_apply_template",{p_template_id:selected,p_page_id:target,p_expected_version:page.content_version});setBusy(false);if(error)return setNotice(error.message);setNotice("模板已应用为新草稿；正式内容未改变");await load()};
 const toggle=async(template:Template)=>{if(!cmsSupabase)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_set_template_active",{p_template_id:template.id,p_active:!template.is_active});setBusy(false);setNotice(error?error.message:template.is_active?"模板已停用":"模板已启用");if(!error)await load()};
 return <div className="cms-template-layout"><section className="cms-card cms-config-card"><h2>从页面创建模板</h2><label className="cms-field"><span>源页面</span><select value={source} onChange={e=>setSource(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.title} · {p.page_type}</option>)}</select></label><label className="cms-field"><span>模板名称</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：智能锁产品详情页"/></label><label className="cms-field"><span>说明</span><textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="cms-button" disabled={!editable||busy||name.trim().length<2} onClick={()=>void create()}>保存为模板</button></section><section className="cms-card cms-config-card"><h2>应用模板</h2><label className="cms-field"><span>模板</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{templates.filter(t=>t.is_active).map(t=><option key={t.id} value={t.id}>{t.name} · {t.page_type}</option>)}</select></label><label className="cms-field"><span>目标页面</span><select value={target} onChange={e=>setTarget(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.title} · v{p.content_version}</option>)}</select></label><p className="cms-muted">应用后只生成新草稿；旧审批与待发布排期自动失效。</p><button className="cms-button" disabled={!editable||busy||!selected||!target} onClick={()=>void apply()}>应用到草稿</button></section><section className="cms-card cms-template-list"><h2>模板库</h2>{templates.map(t=><article key={t.id}><div><strong>{t.name}</strong><span>{t.page_type} · {t.description||"无说明"}</span><small>{new Date(t.updated_at).toLocaleString("zh-CN")}</small></div><button disabled={!editable||busy} onClick={()=>void toggle(t)}>{t.is_active?"停用":"启用"}</button></article>)}{!templates.length?<p className="cms-muted">尚未创建模板。</p>:null}{!editable?<p className="cms-error">当前角色只能查看模板。</p>:null}{notice?<p className={notice.includes("已")?"cms-success":"cms-error"}>{notice}</p>:null}</section></div>;
}
