import {useCallback,useEffect,useMemo,useState} from "react";
import {cmsSupabase} from "./supabase";
import type{CmsRole}from"./cmsGovernance";
import "./PublishCalendar.css";

type Page={id:string;title:string;route:string;workflow_status:string;content_version:number};
type Schedule={id:string;page_id:string;scheduled_for:string;timezone:string;status:"pending"|"running"|"completed"|"cancelled"|"failed";created_at:string;error_message:string|null;cms_pages:{title?:string;route?:string}|null};
const ZONE="Asia/Shanghai";
const statusLabel:Record<Schedule["status"],string>={pending:"待执行",running:"执行中",completed:"已完成",cancelled:"已取消",failed:"失败"};
const pad=(n:number)=>String(n).padStart(2,"0");
const localInput=(date:Date)=>`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;

export default function PublishCalendar({role}:{role:CmsRole}){
 const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const[pages,setPages]=useState<Page[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[pageId,setPageId]=useState(""),[when,setWhen]=useState(()=>localInput(new Date(Date.now()+3600000))),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const canPublish=role==="super_admin"||role==="reviewer";
 const load=useCallback(async()=>{if(!cmsSupabase)return;const start=new Date(month.getFullYear(),month.getMonth(),1),end=new Date(month.getFullYear(),month.getMonth()+1,1);const[{data:p,error:pe},{data:s,error:se}]=await Promise.all([cmsSupabase.from("cms_pages").select("id,title,route,workflow_status,content_version").eq("workflow_status","approved").order("title"),cmsSupabase.from("cms_publish_schedules").select("id,page_id,scheduled_for,timezone,status,created_at,error_message,cms_pages(title,route)").gte("scheduled_for",start.toISOString()).lt("scheduled_for",end.toISOString()).order("scheduled_for")]);setPages((p??[]) as Page[]);setSchedules((s??[]) as unknown as Schedule[]);setPageId(current=>current||String(p?.[0]?.id??""));setNotice(pe?.message??se?.message??"")},[month]);
 useEffect(()=>{void load()},[load]);
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return [...Array(first.getDay()).fill(null),...Array.from({length:count},(_,i)=>new Date(month.getFullYear(),month.getMonth(),i+1))]},[month]);
 const schedule=async()=>{if(!cmsSupabase||!pageId||!when)return;const at=new Date(when);if(Number.isNaN(at.getTime())||at<=new Date())return setNotice("请选择未来时间");setBusy(true);const{error}=await cmsSupabase.rpc("cms_schedule_publish",{p_page_id:pageId,p_scheduled_for:at.toISOString(),p_timezone:ZONE});setBusy(false);if(error)return setNotice(error.message);setNotice("排期已创建；仅已批准且版本未变化的内容会在指定时间发布");await load()};
 const cancel=async(id:string)=>{if(!cmsSupabase)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_cancel_schedule",{p_schedule_id:id});setBusy(false);setNotice(error?error.message:"排期已取消");if(!error)await load()};
 return <div className="cms-calendar-layout"><section className="cms-card cms-calendar-main"><header><div><h2>发布日历</h2><p>数据库保存 UTC；当前按中国标准时间显示。</p></div><div className="cms-calendar-nav"><button onClick={()=>setMonth(v=>new Date(v.getFullYear(),v.getMonth()-1,1))}>‹</button><strong>{month.getFullYear()} 年 {month.getMonth()+1} 月</strong><button onClick={()=>setMonth(v=>new Date(v.getFullYear(),v.getMonth()+1,1))}>›</button></div></header><div className="cms-calendar-week">{["日","一","二","三","四","五","六"].map(day=><span key={day}>{day}</span>)}</div><div className="cms-calendar-grid">{days.map((date,index)=>date?<div className="cms-calendar-day" key={date.toISOString()}><strong>{date.getDate()}</strong>{schedules.filter(item=>new Date(item.scheduled_for).toLocaleDateString("zh-CN",{timeZone:ZONE})===date.toLocaleDateString("zh-CN")).map(item=><span className={`cms-calendar-event ${item.status}`} key={item.id}>{new Date(item.scheduled_for).toLocaleTimeString("zh-CN",{timeZone:ZONE,hour:"2-digit",minute:"2-digit"})} {item.cms_pages?.title??"页面"}</span>)}</div>:<div className="cms-calendar-day empty" key={`empty-${index}`}/>)}</div></section><aside className="cms-card cms-schedule-form"><h2>创建排期</h2><p>只有当前版本已审批的页面可选。</p><label>页面<select value={pageId} onChange={e=>setPageId(e.target.value)}><option value="">请选择</option>{pages.map(page=><option value={page.id} key={page.id}>{page.title} · v{page.content_version}</option>)}</select></label><label>发布时间<input type="datetime-local" value={when} min={localInput(new Date())} onChange={e=>setWhen(e.target.value)}/></label><label>时区<input value="Asia/Shanghai (UTC+8)" readOnly/></label><button className="cms-button" disabled={!canPublish||busy||!pageId} onClick={()=>void schedule()}>{busy?"处理中…":"创建发布排期"}</button>{!canPublish?<p className="cms-error">当前角色只能查看排期，不能创建或取消。</p>:null}{notice?<p className={notice.includes("已")?"cms-success":"cms-error"}>{notice}</p>:null}</aside><section className="cms-card cms-schedule-list"><h2>本月任务</h2>{schedules.length?schedules.map(item=><article key={item.id}><div><strong>{item.cms_pages?.title??item.page_id}</strong><span>{new Date(item.scheduled_for).toLocaleString("zh-CN",{timeZone:ZONE})} · {statusLabel[item.status]}</span>{item.error_message?<small>{item.error_message}</small>:null}</div>{item.status==="pending"&&canPublish?<button disabled={busy} onClick={()=>void cancel(item.id)}>取消</button>:null}</article>):<p className="cms-muted">本月暂无排期。</p>}</section></div>;
}
