import{useEffect,useState}from"react";import{cmsSupabase}from"./supabase";import{can,type CmsRole}from"./cmsGovernance";import"./RedirectManager.css";
type Rule={id:string;source_path:string;target_url:string;http_status:301|302;status:"draft"|"active"|"disabled";version:number;hit_count:number;updated_at:string};
const blank={source_path:"",target_url:"",http_status:301 as const};
export default function RedirectManager({role}:{role:CmsRole}){const[rules,setRules]=useState<Rule[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Rule|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const editable=can(role,"editSeo"),publishable=can(role,"publish");
 const load=async()=>{if(!cmsSupabase)return;const{data,error}=await cmsSupabase.from("cms_redirect_rules").select("*").order("updated_at",{ascending:false});setRules((data??[])as Rule[]);setNotice(error?.message??"")};useEffect(()=>{void load()},[]);
 const save=async()=>{if(!cmsSupabase)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_save_redirect",{p_id:editing?.id??null,p_source_path:form.source_path,p_target_url:form.target_url,p_http_status:form.http_status,p_expected_version:editing?.version??null});setBusy(false);if(error)return setNotice(error.message);setNotice("规则草稿已保存，尚未在线生效");setEditing(null);setForm(blank);await load()};
 const status=async(rule:Rule,next:"active"|"disabled")=>{if(!cmsSupabase)return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_set_redirect_status",{p_id:rule.id,p_status:next,p_expected_version:rule.version});setBusy(false);setNotice(error?error.message:next==="active"?"规则已启用；等待生产网关同步":"规则已停用");if(!error)await load()};
 const edit=(rule:Rule)=>{setEditing(rule);setForm({source_path:rule.source_path,target_url:rule.target_url,http_status:rule.http_status})};
 return <div className="cms-redirect-layout"><section className="cms-card cms-config-card"><h2>{editing?"编辑重定向":"新增重定向"}</h2><label className="cms-field"><span>来源路径</span><input value={form.source_path} onChange={e=>setForm({...form,source_path:e.target.value})} placeholder="/old-page"/></label><label className="cms-field"><span>目标路径或 HTTPS URL</span><input value={form.target_url} onChange={e=>setForm({...form,target_url:e.target.value})} placeholder="/new-page"/></label><label className="cms-field"><span>HTTP 状态</span><select value={form.http_status} onChange={e=>setForm({...form,http_status:Number(e.target.value)as 301|302})}><option value={301}>301 永久</option><option value={302}>302 临时</option></select></label><div className="cms-action-row"><button className="cms-button" disabled={!editable||busy||!form.source_path||!form.target_url} onClick={()=>void save()}>保存草稿</button>{editing?<button className="cms-button secondary" onClick={()=>{setEditing(null);setForm(blank)}}>取消</button>:null}</div><p className="cms-muted">编辑后自动回到草稿。只有审核/发布角色可以启用，服务端网关同步完成后才构成真实 HTTP 重定向。</p></section><section className="cms-card cms-redirect-list"><h2>规则列表</h2>{rules.map(rule=><article key={rule.id}><div><strong>{rule.source_path} → {rule.target_url}</strong><span>{rule.http_status} · {rule.status} · v{rule.version} · 命中 {rule.hit_count}</span></div><div><button disabled={!editable||busy} onClick={()=>edit(rule)}>编辑</button>{rule.status!=="active"?<button disabled={!publishable||busy} onClick={()=>void status(rule,"active")}>启用</button>:<button disabled={!publishable||busy} onClick={()=>void status(rule,"disabled")}>停用</button>}</div></article>)}{!rules.length?<p className="cms-muted">暂无重定向规则。</p>:null}{notice?<p className={notice.includes("已")?"cms-success":"cms-error"}>{notice}</p>:null}</section></div>}
