import{useCallback,useEffect,useState}from"react";
import type{Session}from"@supabase/supabase-js";
import{cmsSupabase}from"./supabase";
import type{CmsRole}from"./cmsGovernance";
type Admin={user_id:string;email:string;role:CmsRole;is_active:boolean;last_sign_in_at:string|null;created_at:string;updated_at:string};
const roles:CmsRole[]=["super_admin","editor","seo","translator","sales","reviewer","viewer"];
const labels:Record<CmsRole,string>={super_admin:"超级管理员",editor:"内容编辑",seo:"SEO",translator:"翻译",sales:"销售",reviewer:"审核发布",viewer:"只读"};
const capabilities=[["读取后台",...roles],["编辑页面","super_admin","editor"],["编辑 SEO","super_admin","editor","seo"],["编辑翻译","super_admin","editor","translator"],["管理素材","super_admin","editor"],["提交审批","super_admin","editor","seo","translator"],["审核与发布","super_admin","reviewer"],["读取询盘","super_admin","sales"],["管理账号","super_admin"]]as string[][];
export default function RoleAdmin({session,role}:{session:Session;role:CmsRole}){
 const[admins,setAdmins]=useState<Admin[]>([]),[email,setEmail]=useState(""),[inviteRole,setInviteRole]=useState<CmsRole>("editor"),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const allowed=role==="super_admin";
 const load=useCallback(async()=>{if(!cmsSupabase||!allowed)return;const{data,error}=await cmsSupabase.rpc("cms_list_admins");setNotice(error?error.message:"");setAdmins((data??[])as Admin[])},[allowed]);useEffect(()=>{void load()},[load]);
 const update=async(admin:Admin,nextRole:CmsRole,nextActive:boolean)=>{if(!cmsSupabase||!confirm(`确认将 ${admin.email} 设为${labels[nextRole]}，状态为${nextActive?"启用":"停用"}？`))return;setBusy(true);const{error}=await cmsSupabase.rpc("cms_set_admin_role",{p_user_id:admin.user_id,p_role:nextRole,p_is_active:nextActive});setBusy(false);setNotice(error?error.message:"管理员权限已更新并写入审计日志");if(!error)await load()};
 const invite=async()=>{if(!cmsSupabase)return;const endpoint=import.meta.env.VITE_CMS_ADMIN_API_URL?.trim();if(!endpoint){setNotice("未配置 VITE_CMS_ADMIN_API_URL；邀请必须由自有服务器使用 service role 执行。");return}const{data:{session:current}}=await cmsSupabase.auth.getSession();if(!current){setNotice("登录已失效");return}setBusy(true);try{const response=await fetch(`${endpoint.replace(/\/$/,"")}/admins/invite`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${current.access_token}`},body:JSON.stringify({email:email.trim(),role:inviteRole,redirectTo:`${location.origin}/cms`})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`邀请失败 (${response.status})`);setEmail("");setNotice("邀请已发送；账号已登记并写入审计日志");await load()}catch(error){setNotice(error instanceof Error?error.message:"邀请失败")}finally{setBusy(false)}};
 if(!allowed)return <div className="cms-card cms-module-empty"><h2>无权管理角色</h2><p>只有超级管理员可以查看管理员列表、邀请账号或调整权限。</p></div>;
 return <div className="cms-role-layout"><section className="cms-card cms-role-invite"><h2>邀请管理员</h2><p>邀请由自有服务器发送；service role 密钥不会进入浏览器。</p><label className="cms-field"><span>邮箱</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label className="cms-field"><span>初始角色</span><select value={inviteRole} onChange={e=>setInviteRole(e.target.value as CmsRole)}>{roles.map(item=><option key={item} value={item}>{labels[item]}</option>)}</select></label><button className="cms-button" disabled={busy||!email.includes("@")} onClick={()=>void invite()}>发送安全邀请</button>{notice?<p className={notice.includes("已")?"cms-success":"cms-error"}>{notice}</p>:null}</section><section className="cms-card cms-role-list"><h2>管理员账号</h2>{admins.map(admin=><article key={admin.user_id}><div><strong>{admin.email}</strong><small>{admin.user_id===session.user.id?"当前账号 · ":""}{admin.last_sign_in_at?`最近登录 ${new Date(admin.last_sign_in_at).toLocaleString("zh-CN")}`:"尚未登录"}</small></div><select value={admin.role} disabled={busy} onChange={e=>void update(admin,e.target.value as CmsRole,admin.is_active)}>{roles.map(item=><option key={item} value={item}>{labels[item]}</option>)}</select><button className={admin.is_active?"danger":""} disabled={busy} onClick={()=>void update(admin,admin.role,!admin.is_active)}>{admin.is_active?"停用":"启用"}</button></article>)}{!admins.length?<p className="cms-muted">数据库迁移完成后，这里显示管理员名单。</p>:null}</section><section className="cms-card cms-capability-matrix"><h2>角色能力矩阵</h2><div className="cms-table-wrap"><table className="cms-table"><thead><tr><th>能力</th>{roles.map(item=><th key={item}>{labels[item]}</th>)}</tr></thead><tbody>{capabilities.map(([cap,...enabled])=><tr key={cap}><td>{cap}</td>{roles.map(item=><td key={item}>{enabled.includes(item)?"✓":"—"}</td>)}</tr>)}</tbody></table></div><p className="cms-muted">最后一个启用中的超级管理员受数据库保护，不能被停用或降级。</p></section></div>
}
