import { BASE } from "@/lib/site-ui";

export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] };

export type ArticleCategory = "Buying Guide" | "Technology" | "Market Insight" | "Company";

export interface Article {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  category: ArticleCategory;
  date: string;
  dateLabel: string;
  readMins: number;
  cover: string;
  excerpt: string;
  keywords: string[];
  body: ArticleBlock[];
}

export const ARTICLES: Article[] = [
  {
    slug: "how-to-choose-security-door-for-projects",
    title: "How to Choose a Security Door for Villa and Residential Projects",
    seoTitle: "How to Choose a Security Door for Projects — Distributor Guide | WONLY",
    description: "A practical framework for distributors and project buyers: security ratings, materials, smart features, finishes and after-sales to specify the right security door.",
    category: "Buying Guide",
    date: "2026-07-08",
    dateLabel: "8 July 2026",
    readMins: 6,
    cover: `${BASE}images/door/gallery/g1-front.jpg`,
    excerpt: "A practical framework for distributors and project buyers — from certified security ratings to finishes, smart features and after-sales support.",
    keywords: ["security door buying guide", "how to choose a security door", "villa security door", "security door for distributors"],
    body: [
      { type: "p", text: "For distributors and project developers, an entrance door is both a safety product and a design statement. Choosing the right door for a market means balancing certified protection, climate durability, aesthetics and total landed cost. This guide walks through the criteria our overseas partners use most when they specify a range." },
      { type: "h2", text: "Start With the Security Rating" },
      { type: "p", text: "The foundation of any security door is its resistance to forced entry. Look past the marketing and check the components that actually stop an intruder." },
      { type: "ul", items: ["Multi-point locking with anti-saw bolts", "Grade C or anti-bump lock cylinders", "Concealed, anti-lift hinges", "A reinforced frame and strike plate, not just a thick leaf"] },
      { type: "h2", text: "Match the Material to the Climate" },
      { type: "p", text: "Coastal and humid markets in the Gulf, Southeast Asia and the Caribbean reward cast-aluminium, which will not rust and holds a premium finish for decades. Drier inland regions can use cold-rolled steel for a lower landed cost. Stocking both lets you serve more project types from one supplier." },
      { type: "h2", text: "Factor in Smart and Convenience Features" },
      { type: "p", text: "Premium residential buyers increasingly expect intelligence at the door: fingerprint, face and app unlocking, auto open-and-close, and a video peephole. These features lift the perceived value of a project and command higher margins than a mechanical door alone." },
      { type: "h2", text: "Do Not Overlook Finishes and Customisation" },
      { type: "p", text: "Colour, wood-grain texture, glass inserts and non-standard sizes are often what wins a villa or hospitality contract. A manufacturer with real OEM and ODM capability can tailor finishes and dimensions to a specific project instead of forcing a fixed catalogue." },
      { type: "h2", text: "Verify Certifications and After-Sales" },
      { type: "p", text: "Ask for CE, ISO and market-specific test reports, and confirm warranty terms and spare-part availability before you commit to a range. A dependable partner supports the door long after it ships." },
      { type: "p", text: "A good manufacturing partner helps you spec the right door for each project rather than pushing a single model. Share your target market and project type with our team and we will recommend a range and pricing within 24 hours." },
    ],
  },
  {
    slug: "cast-aluminium-vs-steel-security-doors",
    title: "Cast-Aluminium vs Steel Security Doors: What Buyers Should Know",
    seoTitle: "Cast-Aluminium vs Steel Security Doors — Buyer Comparison | WONLY",
    description: "The two dominant materials for premium security doors compared on strength, corrosion resistance, weight, cost and best-fit export markets.",
    category: "Technology",
    date: "2026-06-24",
    dateLabel: "24 June 2026",
    readMins: 5,
    cover: `${BASE}images/door/gallery/g3-detail.jpg`,
    excerpt: "The two dominant materials for premium security doors — how they compare on strength, corrosion, weight, cost and the markets each one suits.",
    keywords: ["cast aluminium security door", "steel security door", "security door material comparison", "aluminium vs steel door"],
    body: [
      { type: "p", text: "When partners plan a security-door range, the first technical decision is material. Steel and cast-aluminium both deliver certified protection, but they behave differently in the field and suit different markets. Here is how to think about the trade-off." },
      { type: "h2", text: "Cold-Rolled Steel" },
      { type: "p", text: "Steel offers excellent strength for the cost and is the long-standing standard for security doors. It is ideal for dry, inland climates and price-sensitive projects. Its main limitation is corrosion: without careful coating and maintenance, steel can rust in humid or coastal air." },
      { type: "h2", text: "Cast-Aluminium" },
      { type: "p", text: "Cast-aluminium resists corrosion by nature, so it keeps its finish for decades in salt air and high humidity. It carries fine surface detail and premium textures beautifully, which suits villas and high-end residential. It is lighter than solid steel yet, when engineered with the right internal structure and locking, meets demanding security ratings." },
      { type: "h2", text: "Side by Side" },
      { type: "ul", items: ["Corrosion resistance: cast-aluminium leads, especially in coastal and humid markets", "Cost: steel is typically lower on landed cost", "Finish and detail: cast-aluminium holds premium textures and colours longer", "Weight: cast-aluminium is lighter, easing handling and installation", "Best fit: steel for dry inland value projects, cast-aluminium for premium and coastal projects"] },
      { type: "h2", text: "Which Should You Stock" },
      { type: "p", text: "Most successful distributors carry both: cast-aluminium as the premium, high-margin line for villas and hospitality, and steel for value-led residential. WONLY manufactures both to the same locking and testing standards, so you can serve every project tier from one supplier." },
      { type: "p", text: "Tell us about the climate and price points in your market and we will help you build the right material mix for your range." },
    ],
  },
  {
    slug: "middle-east-security-door-market-2026",
    title: "Security Door and Smart Lock Demand in the Middle East: 2026 Outlook",
    seoTitle: "Middle East Security Door & Smart Lock Market 2026 | WONLY",
    description: "Villa construction, smart-home adoption and the Gulf climate are driving demand for premium cast-aluminium doors and smart locks across the Middle East in 2026.",
    category: "Market Insight",
    date: "2026-06-10",
    dateLabel: "10 June 2026",
    readMins: 6,
    cover: `${BASE}images/gs-saudi-villa.jpg`,
    excerpt: "Why villa construction, smart-home adoption and climate demands are driving Gulf and wider Middle East demand for premium doors and smart locks.",
    keywords: ["Middle East security door market", "smart lock demand Gulf", "security door export Saudi Arabia", "villa doors Middle East"],
    body: [
      { type: "p", text: "The Middle East remains one of the most attractive markets for premium security doors and smart locks. For distributors evaluating where to place inventory in 2026, three forces stand out." },
      { type: "h2", text: "A Villa and Hospitality Construction Wave" },
      { type: "p", text: "Large-scale residential, giga-project and hospitality development across the Gulf continues to generate demand for high-specification entrance doors. Villa and premium apartment buyers expect doors that signal status as well as security, which favours cast-aluminium with rich finishes." },
      { type: "h2", text: "Rapid Smart-Home Adoption" },
      { type: "p", text: "Fingerprint, face and app-based access are moving from novelty to expectation in the region. Buyers increasingly want the entrance to integrate with a wider smart-home system, opening the door to bundled sales of locks, sensors and whole-house intelligence." },
      { type: "h2", text: "A Demanding Climate" },
      { type: "p", text: "Heat, humidity and coastal salt air punish poorly built products. Corrosion-resistant cast-aluminium and sealed, dust-resistant hardware are not luxuries here — they are what keeps a door looking and working well for years, and what protects your brand from warranty claims." },
      { type: "h2", text: "The Opportunity for Distributors" },
      { type: "p", text: "The winning position is a premium, climate-appropriate range backed by a manufacturer that can customise finishes for local taste and supply reliably at project scale. That combination lets you compete on value rather than price alone." },
      { type: "p", text: "WONLY already serves partners across the Middle East and can support you with market-fit products, project pricing and compliance documents. Reach out to discuss your territory." },
    ],
  },
  {
    slug: "wonly-oem-odm-manufacturing-capabilities",
    title: "Inside WONLY's Smart Factories: OEM and ODM for Global Partners",
    seoTitle: "WONLY Smart Factories — Security Door OEM & ODM Manufacturer | WONLY",
    description: "Five manufacturing bases, robotic production lines and full OEM/ODM flexibility — how WONLY supports distributors and private-label partners worldwide.",
    category: "Company",
    date: "2026-05-27",
    dateLabel: "27 May 2026",
    readMins: 5,
    cover: `${BASE}images/mfg-hero.jpg`,
    excerpt: "Five manufacturing bases, robotic production lines and full OEM/ODM flexibility — how WONLY supports distributors and private-label partners worldwide.",
    keywords: ["security door OEM manufacturer", "smart lock ODM factory", "private label security door", "WONLY manufacturing"],
    body: [
      { type: "p", text: "Behind every WONLY door and lock is a vertically integrated manufacturing base built for scale and consistency. For partners choosing a long-term supplier, here is what that means in practice." },
      { type: "h2", text: "Scale You Can Rely On" },
      { type: "p", text: "With multiple manufacturing bases and robotic production lines, WONLY produces millions of steel doors, wooden doors and smart locks each year. That capacity keeps lead times predictable and lets us support project-scale orders without quality drift." },
      { type: "h2", text: "Real OEM and ODM Flexibility" },
      { type: "p", text: "Partners can order WONLY products under our brand, apply their own private label, or co-develop a product tailored to their market. Finishes, dimensions, hardware and packaging can all be adapted, so your range feels made for your customers rather than pulled from a fixed catalogue." },
      { type: "h2", text: "Quality and Certification Built In" },
      { type: "p", text: "In-line inspection, dedicated testing and international certifications mean the door that ships matches the specification you approved. Compliance documents are available to support customs clearance and project tenders in your market." },
      { type: "h2", text: "A Partnership, Not Just a Purchase Order" },
      { type: "p", text: "From first sample to after-sales support, our overseas team works as an extension of yours — helping you spec ranges, win projects and protect your brand in the field." },
      { type: "p", text: "If you are evaluating a long-term door and lock supplier, we would welcome the chance to share our capabilities and discuss how we can support your growth." },
    ],
  },
  {
    slug: "how-to-choose-a-smart-lock-for-your-range",
    title: "How to Choose a Smart Lock for Your Product Range: A Distributor's Checklist",
    seoTitle: "How to Choose a Smart Lock — Distributor Buying Checklist | WONLY",
    description: "Access methods, security, battery life, durability and integration — the checklist distributors use to select smart locks that sell and last in export markets.",
    category: "Buying Guide",
    date: "2026-05-13",
    dateLabel: "13 May 2026",
    readMins: 6,
    cover: `${BASE}images/lock-s80-render.webp`,
    excerpt: "Access methods, security, battery life, durability and smart-home integration — a practical checklist for selecting smart locks that sell and last.",
    keywords: ["smart lock buying guide", "how to choose a smart lock", "smart lock for distributors", "fingerprint door lock"],
    body: [
      { type: "p", text: "A smart lock is often the first smart-home product a customer buys, so it shapes their impression of your whole range. Choosing the right models means looking past the feature list to how the lock performs day after day. Here is the checklist our partners use." },
      { type: "h2", text: "Access Methods Buyers Expect" },
      { type: "p", text: "The best-selling locks give users several ways in, plus a reliable backup." },
      { type: "ul", items: ["Fingerprint for everyday speed", "Face or palm recognition for hands-free entry", "PIN code with anti-peep protection", "Phone app and temporary passwords for guests", "A physical key or emergency power backup for peace of mind"] },
      { type: "h2", text: "Security That Holds Up" },
      { type: "p", text: "Look for encrypted communication, tamper and pry alarms, auto-relock and false-code lockout. These are what separate a serious security product from a gadget." },
      { type: "h2", text: "Power and Reliability" },
      { type: "p", text: "Long battery life, clear low-battery alerts and an emergency power option (such as a USB backup) prevent the lockouts that generate complaints and returns." },
      { type: "h2", text: "Build Quality and Climate" },
      { type: "p", text: "For outdoor or exposed doors, confirm weatherproofing and corrosion-resistant materials. A lock that fades or jams in heat and humidity will damage your brand in demanding markets." },
      { type: "h2", text: "Smart-Home Integration" },
      { type: "p", text: "If your customers want a connected home, a lock that links to a wider smart-home or access system opens up bundled sales of sensors, cameras and whole-house control." },
      { type: "p", text: "WONLY smart locks are built to these standards and can be tailored for your market. Tell us your target segment and we will recommend a range and pricing." },
    ],
  },
  {
    slug: "how-smart-lock-access-works",
    title: "Fingerprint, Face and App Unlock: How Modern Smart Lock Access Works",
    seoTitle: "How Smart Lock Access Works — Fingerprint, Face & App | WONLY",
    description: "A clear explanation of the access technologies inside modern smart locks: biometrics, encrypted app control and secure fallbacks, for buyers and partners.",
    category: "Technology",
    date: "2026-04-29",
    dateLabel: "29 April 2026",
    readMins: 5,
    cover: `${BASE}images/lock-s80.webp`,
    excerpt: "A clear look at the technologies inside modern smart locks — biometrics, encrypted app control and the fallbacks that keep users safe.",
    keywords: ["how smart locks work", "fingerprint door lock technology", "face recognition lock", "app controlled door lock"],
    body: [
      { type: "p", text: "Modern smart locks combine several access technologies so users can choose the method that suits the moment. Understanding how each one works helps you explain the value to your customers." },
      { type: "h2", text: "Fingerprint Recognition" },
      { type: "p", text: "A capacitive or optical sensor reads the ridges of a finger and matches them against stored templates in under a second. Quality sensors handle dry, wet or worn fingerprints and store data only on the lock, not in the cloud." },
      { type: "h2", text: "Face and Palm Recognition" },
      { type: "p", text: "3D face and palm-vein recognition let users unlock hands-free, which is ideal when carrying bags or groceries. Depth-sensing cameras resist being fooled by a photo, keeping convenience and security together." },
      { type: "h2", text: "App and Remote Control" },
      { type: "p", text: "A companion app unlocks the door, issues time-limited passwords for guests or cleaners, and logs who came and went. Communication is encrypted so codes cannot be intercepted." },
      { type: "h2", text: "Secure Fallbacks" },
      { type: "p", text: "Good locks never leave a user stranded. Common fallbacks include:" },
      { type: "ul", items: ["An anti-peep PIN keypad", "A concealed physical key", "An emergency external power port", "Auto-relock and tamper alarms"] },
      { type: "p", text: "WONLY engineers these layers into every smart lock. Reach out for full specifications and integration options." },
    ],
  },
  {
    slug: "southeast-asia-security-door-market",
    title: "Security Door Opportunities in Southeast Asia: Villas, Condos and Climate",
    seoTitle: "Southeast Asia Security Door Market — Villas & Condos | WONLY",
    description: "Urbanisation, condo and villa development and a hot, humid climate are shaping demand for corrosion-resistant security doors and smart locks across Southeast Asia.",
    category: "Market Insight",
    date: "2026-04-15",
    dateLabel: "15 April 2026",
    readMins: 5,
    cover: `${BASE}images/gs-barbados.jpg`,
    excerpt: "Urbanisation, condo and villa development and a humid tropical climate are shaping demand for corrosion-resistant doors and smart locks across the region.",
    keywords: ["Southeast Asia security door market", "security door Vietnam Philippines", "condo smart lock Asia", "humid climate door"],
    body: [
      { type: "p", text: "Southeast Asia is one of the fastest-moving regions for residential security. For distributors, three characteristics make it a strong market for premium doors and smart locks." },
      { type: "h2", text: "Urbanisation and New-Build Housing" },
      { type: "p", text: "Rapid urban growth across Vietnam, the Philippines, Indonesia and neighbouring markets is producing waves of condominium and landed-housing projects, each of which needs entrance doors and locks at scale." },
      { type: "h2", text: "A Hot, Humid Climate" },
      { type: "p", text: "High humidity and coastal air make corrosion resistance essential. Cast-aluminium doors and well-sealed smart locks keep their finish and function far longer here than untreated steel or budget hardware." },
      { type: "h2", text: "Fast Smart-Home Adoption" },
      { type: "p", text: "The region is mobile-first and quick to adopt app-based living. Fingerprint and app locks are increasingly expected in new condos, which supports bundled sales across doors, locks and home devices." },
      { type: "h2", text: "The Opportunity" },
      { type: "p", text: "A climate-appropriate, smart-ready range positioned for mid-to-premium housing gives distributors room to grow on value rather than price. WONLY can supply and customise for local project requirements." },
      { type: "p", text: "Talk to our team about building a Southeast Asia range suited to your customers and climate." },
    ],
  },
  {
    slug: "security-door-ratings-and-certifications",
    title: "Understanding Security Door Ratings and Certifications for Import Markets",
    seoTitle: "Security Door Ratings & Certifications for Importers | WONLY",
    description: "CE, ISO, lock grades and burglar-resistance classes explained: what the ratings mean and which certifications importers should request from a door supplier.",
    category: "Buying Guide",
    date: "2026-04-02",
    dateLabel: "2 April 2026",
    readMins: 6,
    cover: `${BASE}images/mfg-inspect.jpg`,
    excerpt: "CE, ISO, lock grades and burglar-resistance classes explained — what the ratings mean and which documents importers should request from a supplier.",
    keywords: ["security door certifications", "CE security door", "burglar resistance class", "lock grade C", "security door standards import"],
    body: [
      { type: "p", text: "Ratings and certifications protect your customers and your customs clearance. Knowing what each one means helps you buy with confidence and market with credibility." },
      { type: "h2", text: "Lock Cylinder Grades" },
      { type: "p", text: "Cylinder grades (commonly A, B and C, with C the highest) indicate resistance to picking, bumping and drilling. For security doors, a Grade C or anti-bump cylinder is the sensible baseline." },
      { type: "h2", text: "Burglar-Resistance Classes" },
      { type: "p", text: "Forced-entry classes describe how long a door resists a determined attack with tools. Higher classes suit high-risk or high-value properties, while mid classes fit most residential projects." },
      { type: "h2", text: "Product and Quality Certifications" },
      { type: "p", text: "CE marking supports sale into many markets, while ISO quality-management certification signals consistent factory processes. Market-specific approvals may also apply depending on where you import." },
      { type: "h2", text: "What to Request From Your Supplier" },
      { type: "ul", items: ["CE and ISO documentation", "Lock cylinder grade and test reports", "Burglar-resistance or forced-entry class where available", "Material and coating specifications", "Warranty terms and spare-part support"] },
      { type: "p", text: "WONLY supplies the compliance documentation partners need for customs and tenders. Ask us for the certification pack relevant to your market." },
    ],
  },
  {
    slug: "africa-security-door-demand",
    title: "Africa's Growing Demand for Durable, Affordable Security Doors",
    seoTitle: "Africa Security Door Market — Durable & Affordable | WONLY",
    description: "Rapid construction, urban growth and a focus on value durability are driving African demand for steel and cast-aluminium security doors and reliable smart locks.",
    category: "Market Insight",
    date: "2026-03-19",
    dateLabel: "19 March 2026",
    readMins: 5,
    cover: `${BASE}images/gs-egypt-cbd.jpg`,
    excerpt: "Rapid construction, urban growth and a focus on durable value are driving African demand for security doors and reliable smart locks.",
    keywords: ["Africa security door market", "security door export Africa", "affordable security door", "door supplier Nigeria Kenya"],
    body: [
      { type: "p", text: "Across many African markets, a fast-growing middle class and steady construction are lifting demand for security doors that balance protection, durability and price. For exporters, the region rewards the right value proposition." },
      { type: "h2", text: "Construction and Urban Growth" },
      { type: "p", text: "New residential and commercial development in cities across the continent creates consistent demand for entrance doors, from value steel doors to premium cast-aluminium for higher-end projects." },
      { type: "h2", text: "Value and Durability Come First" },
      { type: "p", text: "Buyers prioritise doors that deliver dependable security and long service life for the price. A supplier who can offer strong steel value lines alongside premium options wins a wider share of projects." },
      { type: "h2", text: "The Rising Role of Smart Locks" },
      { type: "p", text: "As smartphone use spreads, interest in fingerprint and app locks is growing in urban and premium segments, adding an upsell path on top of the core door business." },
      { type: "h2", text: "The Opportunity for Distributors" },
      { type: "p", text: "A tiered range, reliable supply and clear after-sales support let distributors build trust and repeat business. WONLY manufactures at the scale and price points African markets need." },
      { type: "p", text: "Contact our team to discuss a product mix and pricing tailored to your African market." },
    ],
  },
];

export const getArticle = (slug: string): Article | undefined =>
  ARTICLES.find((a) => a.slug === slug);

export const relatedArticles = (slug: string, n = 3): Article[] =>
  ARTICLES.filter((a) => a.slug !== slug).slice(0, n);
