import { BASE } from "@/lib/site-ui";

export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul"; items: string[] };

export type ArticleCategory = "Buying Guide" | "Technology" | "Market Insight" | "Company";

export interface Article {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  category: ArticleCategory;
  date: string;
  dateLabel: string;
  readMins: number;
  cover: string;
  excerpt: string;
  keywords: string[];
  body: ArticleBlock[];
}

export const ARTICLES: Article[] = [
  {
    slug: "fire-rated-doors-explained",
    title: "Fire-Rated Doors Explained: EN 1634 and 60 vs 90 Minutes",
    seoTitle: "Fire-Rated Doors Explained: EN 1634 & 60 vs 90 Minutes | WONLY",
    description: "Fire-rated door ratings made simple — EN 1634 testing, integrity vs insulation, 30/60/90/120 minutes, where they're required and how to specify the right one.",
    category: "Buying Guide",
    date: "2026-07-22",
    dateLabel: "22 July 2026",
    readMins: 6,
    cover: `${BASE}images/alu-t200.webp`,
    excerpt: "EN 1634 testing, integrity vs insulation, and 30/60/90/120 minutes — how fire-door ratings work and how to specify the right one for hotels, hospitals and apartments.",
    keywords: ["fire rated door ratings", "EN 1634", "60 vs 90 minute fire door", "fire door integrity insulation", "fire rated doors explained"],
    body: [
      { type: "p", text: "A fire-rated door is a life-safety product: in a fire it must hold long enough for people to escape and for the fire to be contained. But “fire-rated” only means something when it is tied to a tested rating. This guide explains fire-door ratings, the EN 1634 standard, and how to specify the right one for hotels, hospitals, apartments and public projects." },
      { type: "h2", text: "What a Fire Rating Actually Measures" },
      { type: "p", text: "A fire door is tested to a recognised standard — EN 1634-1 in Europe and most export markets, or UL 10C in North America — and rated by how many minutes it holds back fire. The common ratings are 30, 60, 90 and 120 minutes. The higher the number, the longer the door contains fire and smoke." },
      { type: "h2", text: "Integrity vs Insulation: E and EI" },
      { type: "ul", items: ["E — Integrity: the door stops flames and hot gases passing through for the rated time", "I — Insulation: the door also limits heat transfer to the unexposed side, so the escape route stays usable"] },
      { type: "p", text: "So a door rated EI 90 provides both integrity and insulation for 90 minutes, while an E 90 door provides integrity only. For escape corridors and compartment walls, EI ratings are usually required." },
      { type: "h2", text: "60 vs 90 Minutes — Which Do You Need?" },
      { type: "ul", items: ["30 min (EI 30) — doors within dwellings and low-risk internal openings", "60 min (EI 60) — apartment entrances, corridors and common areas", "90 min (EI 90) — higher-risk compartments, commercial and institutional, and many export codes", "120 min (EI 120) — critical separation such as plant rooms and high-rise cores"] },
      { type: "p", text: "The exact requirement is set by local building code and the building's fire strategy, so always confirm the specified rating for each opening before ordering. In many Gulf, Southeast Asian and Central Asian projects, 90-minute doors are the practical benchmark." },
      { type: "h2", text: "Fire Rating Is Not a Security Rating" },
      { type: "p", text: "A common buyer mistake is assuming a fire door is also a security door. They are two separate tests: fire performance (EN 1634) and burglar resistance (EN 1627 / GB 17565). The good news is that a well-engineered door can carry both. For entrances that need protection and fire compliance — hotels, hospitals, apartments — specify a door certified for both." },
      { type: "h2", text: "How to Specify a Fire-Rated Door Correctly" },
      { type: "ul", items: ["Confirm the rating per opening (E vs EI, and minutes) from the fire strategy", "Buy the certified doorset, not just the leaf — the rating applies to the door, frame, seals and hardware as a tested set", "Use the tested intumescent seals and closers — substitutions void the rating", "Get the test certificate and the matching hardware schedule", "Check destination-market approval for your project"] },
      { type: "h2", text: "WONLY Fire-Rated Doors" },
      { type: "p", text: "WONLY manufactures dedicated Engineering Fire Doors and Medical-Grade Doors alongside its security range:" },
      { type: "ul", items: ["EN 1634 fire rating — 90-minute integrity, compliant with Gulf, SE Asia and Central Asia codes", "GB 17565 Class A security grade on applicable models, so one door can be both fire-rated and burglar-resistant", "200,000+ cycle testing and certification to ISO 9001/14001, CE, UL, CMA and CSPA", "Backed by 30 years of manufacturing and 1,000+ patents (listed — SSE 605268)"] },
      { type: "h2", text: "FAQ" },
      { type: "p", text: "What does a 90-minute fire door mean? It has passed EN 1634 testing and holds back fire (and, for an EI rating, heat) for 90 minutes, giving time to evacuate and contain the fire." },
      { type: "p", text: "Can a door be both fire-rated and security-rated? Yes — a well-engineered doorset can carry an EN 1634 fire rating and an EN 1627 / GB 17565 security grade at the same time." },
      { type: "p", text: "Specifying fire-rated doors for a hotel, hospital or apartment project? WONLY supplies certified fire-rated and dual-rated doors for export, with full test documentation for customs and tenders." },
    ],
  },
  {
    slug: "how-to-choose-security-door-for-projects",
    title: "How to Choose a Security Door for Villa and Residential Projects",
    seoTitle: "How to Choose a Security Door for Projects — Buyer's Guide | WONLY",
    description: "How to choose a security door for a project or product range — rating, material, fire, climate, certification and supplier checks in one B2B buyer's guide.",
    category: "Buying Guide",
    date: "2026-07-08",
    dateLabel: "8 July 2026",
    readMins: 7,
    cover: `${BASE}images/door/gallery/g1-front.jpg`,
    excerpt: "A step-by-step B2B buyer's guide — matching security rating, material, fire, certification and supplier reliability to your market.",
    keywords: ["how to choose a security door", "security door buyer's guide", "security door for projects", "import security doors", "security door supplier"],
    body: [
      { type: "p", text: "For a distributor, developer or project buyer, choosing a security door is not about picking a look — it is about matching security, compliance, climate and supplier reliability to your market. Get it right and you win repeat orders; get it wrong and you inherit callbacks and warranty claims. Here is a practical, step-by-step buyer's guide." },
      { type: "h2", text: "1. Start With the Security Rating, Not the Price" },
      { type: "p", text: "The first question is how secure the door needs to be. Specify a verified burglar-resistance rating — the European EN 1627 RC classes or China's GB 17565 grades — instead of a vague “high security” claim. Residential low-rise usually calls for RC2–RC3; commercial and institutional work needs RC4 or higher. Always ask for the test certificate, not just a spec sheet." },
      { type: "h2", text: "2. Match the Material to the Climate and Market" },
      { type: "ul", items: ["Cast aluminium — won't rust, near-zero maintenance, sculptural designs; ideal for coastal, humid and premium projects (Gulf, SE Asia, coastal Africa)", "Steel — maximum strength per cost; best for dry, sheltered, value-driven volume work"] },
      { type: "p", text: "The wrong material in a salt-air market means rust bleed and returns, so match the metal to the environment before anything else." },
      { type: "h2", text: "3. Add a Fire Rating Where the Building Requires It" },
      { type: "p", text: "Hotels, hospitals, apartment corridors and public buildings usually mandate a fire rating alongside security. Confirm whether your project needs EN 1634 fire performance (for example 60- or 90-minute integrity) before you specify — retrofitting compliance later is expensive." },
      { type: "h2", text: "4. Check Certification for the Destination Market" },
      { type: "p", text: "A door that is compliant in one country may not clear customs or code in another. Confirm the door carries the certifications your market and insurer accept — commonly ISO 9001, CE, UL and regional fire/security approvals — and ask which export codes it already meets (Gulf, SE Asia, Central Asia)." },
      { type: "h2", text: "5. Scrutinise the Lock and Hardware" },
      { type: "p", text: "The lock is the most-attacked point. Look for multi-point locking, an anti-drill / anti-bump cylinder, reinforced hinges, and hardware cycle-tested to a high count so it survives years of daily use." },
      { type: "h2", text: "6. Vet the Supplier, Not Just the Sample" },
      { type: "ul", items: ["Track record — years in business, listed or audited status, patents", "Capacity — a real manufacturing base and output, not a trading company", "Range — can they cover residential, fire, commercial and medical in one order", "Support — certification packs, spare parts and after-sales"] },
      { type: "h2", text: "How WONLY Supports Project and Distributor Buyers" },
      { type: "p", text: "WONLY has built security doors since 1996 and is a listed manufacturer (SSE: 605268) with 1,000+ patents and 30 years without a major safety incident — a real factory, not a trader. Its doors are:" },
      { type: "ul", items: ["GB 17565 Class A (highest grade) and EN 1634 90-minute fire-rated, compliant with Gulf, SE Asia and Central Asia codes", "200,000+ cycle tested and forced-entry tested; certified to ISO 9001/14001, CE, UL, CMA and CSPA", "Available across a full range — X70 robotic, 4.0 Global Series, K300 Pro, Engineering Fire Doors and Medical-Grade — so one supplier covers villas, projects and institutions"] },
      { type: "h2", text: "FAQ" },
      { type: "p", text: "What is the single most important factor when choosing a security door? A verified burglar-resistance rating (EN 1627 or GB 17565) matched to the real risk level — everything else builds on that." },
      { type: "p", text: "Should I buy aluminium or steel? Aluminium for coastal, humid and premium projects; steel for dry, sheltered, value-driven volume work." },
    ],
  },
  {
    slug: "cast-aluminium-vs-steel-security-doors",
    title: "Cast-Aluminium vs Steel Security Doors: What Buyers Should Know",
    seoTitle: "Cast-Aluminium vs Steel Security Doors: Buyer Comparison | WONLY",
    description: "Cast-aluminium vs steel security doors compared on security, corrosion, weather, weight, cost and best-fit markets — how to pick the right door material.",
    category: "Technology",
    date: "2026-06-24",
    dateLabel: "24 June 2026",
    readMins: 6,
    cover: `${BASE}images/door/gallery/g3-detail.jpg`,
    excerpt: "Which material for which market — cast-aluminium vs steel compared on strength, corrosion, weather, cost and the projects each one suits.",
    keywords: ["cast aluminium vs steel security door", "aluminium security door", "steel security door", "security door material", "corrosion resistant door"],
    body: [
      { type: "p", text: "Steel has been the default security-door material for decades — but cast aluminium has become the premium choice for villas, coastal projects and export markets. For importers and project buyers, the right material depends on climate, budget and positioning. Here is a clear, practical comparison." },
      { type: "h2", text: "The Short Answer" },
      { type: "ul", items: ["Steel — maximum raw strength per dollar, the cost-effective workhorse for standard security", "Cast aluminium — trades a little raw hardness for corrosion resistance, sculptural design and near-zero maintenance; ideal for humid, coastal and high-end projects"] },
      { type: "p", text: "Both can achieve strong burglar-resistance ratings; the difference is longevity, environment and looks — not security alone." },
      { type: "h2", text: "Side by Side" },
      { type: "ul", items: ["Corrosion and rust: cast aluminium does not rust; steel rusts wherever the coating is breached", "Best climate: aluminium for coastal, humid and tropical; steel for dry, sheltered entries", "Design freedom: aluminium casts into sculptural, textured forms; steel is mostly flat or stamped", "Weight: aluminium is lighter; steel is heavier", "Maintenance: aluminium near-zero; steel needs repaint or retouch to prevent rust", "Cost and positioning: steel for value and volume; aluminium for premium villas and flagship projects"] },
      { type: "h2", text: "Why Cast Aluminium Wins in Export Markets" },
      { type: "p", text: "For buyers in the Middle East, Southeast Asia, coastal Africa and Latin America, weather is the real enemy of a door. Salt air and humidity attack steel at any coating flaw, causing rust bleed and callbacks. Cast aluminium will not rust, holds its finish and needs almost no maintenance — protecting your brand and cutting warranty claims. Its casting process also enables sculptural, high-value designs that support a premium price point." },
      { type: "h2", text: "Where Steel Still Makes Sense" },
      { type: "p", text: "Steel remains a smart choice when the priority is maximum strength at the lowest cost and the door sits in a dry, protected location — internal or well-sheltered entries in value-focused residential and commercial projects. With a quality powder-coat and good detailing, steel gives dependable security at volume pricing." },
      { type: "h2", text: "Security Is Decided by Engineering, Not Just the Metal" },
      { type: "ul", items: ["A verified burglar-resistance rating (EN 1627 / GB 17565)", "Multi-point locking with an anti-drill, anti-bump cylinder", "A strong frame, hinges and reinforcement", "200,000+ cycle testing so the hardware lasts"] },
      { type: "p", text: "A rated cast-aluminium door and a rated steel door can both stop a determined intruder — so choose the material for the environment and market, and let the rating and hardware guarantee the security." },
      { type: "h2", text: "How WONLY Builds Cast-Aluminium Doors" },
      { type: "p", text: "WONLY's flagship doors — the X70 robotic, 4.0 Global Series and K300 Pro — use a cast-aluminium construction over a steel core with climate-adapted engineering:" },
      { type: "ul", items: ["Won't rust — built for Gulf, SE Asia and coastal projects", "Hurricane-rated to wind Class 12", "Class A security grade and EN 1634 90-minute fire rating on applicable series", "200,000+ cycle tested; certified to ISO 9001/14001, CE, UL, CMA and CSPA", "Backed by 1,000+ patents and 30 years of engineering (listed — SSE 605268)"] },
      { type: "h2", text: "FAQ" },
      { type: "p", text: "Are aluminium security doors as secure as steel? Yes, when they carry the same burglar-resistance rating — security comes from the door's rated system, not the base metal alone." },
      { type: "p", text: "Do aluminium doors rust? No. Aluminium does not rust, which makes cast-aluminium doors ideal for coastal and humid climates where steel would corrode." },
    ],
  },
  {
    slug: "middle-east-security-door-market-2026",
    title: "Security Door and Smart Lock Demand in the Middle East: 2026 Outlook",
    seoTitle: "Middle East Security Door & Smart Lock Market 2026 | WONLY",
    description: "Villa construction, smart-home adoption and the Gulf climate are driving demand for premium cast-aluminium doors and smart locks across the Middle East in 2026.",
    category: "Market Insight",
    date: "2026-06-10",
    dateLabel: "10 June 2026",
    readMins: 6,
    cover: `${BASE}images/gs-saudi-villa.jpg`,
    excerpt: "Why villa construction, smart-home adoption and climate demands are driving Gulf and wider Middle East demand for premium doors and smart locks.",
    keywords: ["Middle East security door market", "smart lock demand Gulf", "security door export Saudi Arabia", "villa doors Middle East"],
    body: [
      { type: "p", text: "The Middle East remains one of the most attractive markets for premium security doors and smart locks. For distributors evaluating where to place inventory in 2026, three forces stand out." },
      { type: "h2", text: "A Villa and Hospitality Construction Wave" },
      { type: "p", text: "Large-scale residential, giga-project and hospitality development across the Gulf continues to generate demand for high-specification entrance doors. Villa and premium apartment buyers expect doors that signal status as well as security, which favours cast-aluminium with rich finishes." },
      { type: "h2", text: "Rapid Smart-Home Adoption" },
      { type: "p", text: "Fingerprint, face and app-based access are moving from novelty to expectation in the region. Buyers increasingly want the entrance to integrate with a wider smart-home system, opening the door to bundled sales of locks, sensors and whole-house intelligence." },
      { type: "h2", text: "A Demanding Climate" },
      { type: "p", text: "Heat, humidity and coastal salt air punish poorly built products. Corrosion-resistant cast-aluminium and sealed, dust-resistant hardware are not luxuries here — they are what keeps a door looking and working well for years, and what protects your brand from warranty claims." },
      { type: "h2", text: "The Opportunity for Distributors" },
      { type: "p", text: "The winning position is a premium, climate-appropriate range backed by a manufacturer that can customise finishes for local taste and supply reliably at project scale. That combination lets you compete on value rather than price alone." },
      { type: "p", text: "WONLY already serves partners across the Middle East and can support you with market-fit products, project pricing and compliance documents. Reach out to discuss your territory." },
    ],
  },
  {
    slug: "wonly-oem-odm-manufacturing-capabilities",
    title: "Inside WONLY's Smart Factories: OEM and ODM for Global Partners",
    seoTitle: "WONLY Smart Factories — Security Door OEM & ODM Manufacturer | WONLY",
    description: "Five manufacturing bases, robotic production lines and full OEM/ODM flexibility — how WONLY supports distributors and private-label partners worldwide.",
    category: "Company",
    date: "2026-05-27",
    dateLabel: "27 May 2026",
    readMins: 5,
    cover: `${BASE}images/mfg-hero.jpg`,
    excerpt: "Five manufacturing bases, robotic production lines and full OEM/ODM flexibility — how WONLY supports distributors and private-label partners worldwide.",
    keywords: ["security door OEM manufacturer", "smart lock ODM factory", "private label security door", "WONLY manufacturing"],
    body: [
      { type: "p", text: "Behind every WONLY door and lock is a vertically integrated manufacturing base built for scale and consistency. For partners choosing a long-term supplier, here is what that means in practice." },
      { type: "h2", text: "Scale You Can Rely On" },
      { type: "p", text: "With multiple manufacturing bases and robotic production lines, WONLY produces millions of steel doors, wooden doors and smart locks each year. That capacity keeps lead times predictable and lets us support project-scale orders without quality drift." },
      { type: "h2", text: "Real OEM and ODM Flexibility" },
      { type: "p", text: "Partners can order WONLY products under our brand, apply their own private label, or co-develop a product tailored to their market. Finishes, dimensions, hardware and packaging can all be adapted, so your range feels made for your customers rather than pulled from a fixed catalogue." },
      { type: "h2", text: "Quality and Certification Built In" },
      { type: "p", text: "In-line inspection, dedicated testing and international certifications mean the door that ships matches the specification you approved. Compliance documents are available to support customs clearance and project tenders in your market." },
      { type: "h2", text: "A Partnership, Not Just a Purchase Order" },
      { type: "p", text: "From first sample to after-sales support, our overseas team works as an extension of yours — helping you spec ranges, win projects and protect your brand in the field." },
      { type: "p", text: "If you are evaluating a long-term door and lock supplier, we would welcome the chance to share our capabilities and discuss how we can support your growth." },
    ],
  },
  {
    slug: "how-to-choose-a-smart-lock-for-your-range",
    title: "How to Choose a Smart Lock for Your Product Range: A Distributor's Checklist",
    seoTitle: "How to Choose a Smart Lock — Distributor Buying Checklist | WONLY",
    description: "Access methods, security, battery life, durability and integration — the checklist distributors use to select smart locks that sell and last in export markets.",
    category: "Buying Guide",
    date: "2026-05-13",
    dateLabel: "13 May 2026",
    readMins: 6,
    cover: `${BASE}images/lock-s80-render.webp`,
    excerpt: "Access methods, security, battery life, durability and smart-home integration — a practical checklist for selecting smart locks that sell and last.",
    keywords: ["smart lock buying guide", "how to choose a smart lock", "smart lock for distributors", "fingerprint door lock"],
    body: [
      { type: "p", text: "A smart lock is often the first smart-home product a customer buys, so it shapes their impression of your whole range. Choosing the right models means looking past the feature list to how the lock performs day after day. Here is the checklist our partners use." },
      { type: "h2", text: "Access Methods Buyers Expect" },
      { type: "p", text: "The best-selling locks give users several ways in, plus a reliable backup." },
      { type: "ul", items: ["Fingerprint for everyday speed", "Face or palm recognition for hands-free entry", "PIN code with anti-peep protection", "Phone app and temporary passwords for guests", "A physical key or emergency power backup for peace of mind"] },
      { type: "h2", text: "Security That Holds Up" },
      { type: "p", text: "Look for encrypted communication, tamper and pry alarms, auto-relock and false-code lockout. These are what separate a serious security product from a gadget." },
      { type: "h2", text: "Power and Reliability" },
      { type: "p", text: "Long battery life, clear low-battery alerts and an emergency power option (such as a USB backup) prevent the lockouts that generate complaints and returns." },
      { type: "h2", text: "Build Quality and Climate" },
      { type: "p", text: "For outdoor or exposed doors, confirm weatherproofing and corrosion-resistant materials. A lock that fades or jams in heat and humidity will damage your brand in demanding markets." },
      { type: "h2", text: "Smart-Home Integration" },
      { type: "p", text: "If your customers want a connected home, a lock that links to a wider smart-home or access system opens up bundled sales of sensors, cameras and whole-house control." },
      { type: "p", text: "WONLY smart locks are built to these standards and can be tailored for your market. Tell us your target segment and we will recommend a range and pricing." },
    ],
  },
  {
    slug: "how-smart-lock-access-works",
    title: "Fingerprint, Face and App Unlock: How Modern Smart Lock Access Works",
    seoTitle: "How Smart Lock Access Works — Fingerprint, Face & App | WONLY",
    description: "A clear explanation of the access technologies inside modern smart locks: biometrics, encrypted app control and secure fallbacks, for buyers and partners.",
    category: "Technology",
    date: "2026-04-29",
    dateLabel: "29 April 2026",
    readMins: 5,
    cover: `${BASE}images/lock-s80.webp`,
    excerpt: "A clear look at the technologies inside modern smart locks — biometrics, encrypted app control and the fallbacks that keep users safe.",
    keywords: ["how smart locks work", "fingerprint door lock technology", "face recognition lock", "app controlled door lock"],
    body: [
      { type: "p", text: "Modern smart locks combine several access technologies so users can choose the method that suits the moment. Understanding how each one works helps you explain the value to your customers." },
      { type: "h2", text: "Fingerprint Recognition" },
      { type: "p", text: "A capacitive or optical sensor reads the ridges of a finger and matches them against stored templates in under a second. Quality sensors handle dry, wet or worn fingerprints and store data only on the lock, not in the cloud." },
      { type: "h2", text: "Face and Palm Recognition" },
      { type: "p", text: "3D face and palm-vein recognition let users unlock hands-free, which is ideal when carrying bags or groceries. Depth-sensing cameras resist being fooled by a photo, keeping convenience and security together." },
      { type: "h2", text: "App and Remote Control" },
      { type: "p", text: "A companion app unlocks the door, issues time-limited passwords for guests or cleaners, and logs who came and went. Communication is encrypted so codes cannot be intercepted." },
      { type: "h2", text: "Secure Fallbacks" },
      { type: "p", text: "Good locks never leave a user stranded. Common fallbacks include:" },
      { type: "ul", items: ["An anti-peep PIN keypad", "A concealed physical key", "An emergency external power port", "Auto-relock and tamper alarms"] },
      { type: "p", text: "WONLY engineers these layers into every smart lock. Reach out for full specifications and integration options." },
    ],
  },
  {
    slug: "southeast-asia-security-door-market",
    title: "Security Door Opportunities in Southeast Asia: Villas, Condos and Climate",
    seoTitle: "Southeast Asia Security Door Market — Villas & Condos | WONLY",
    description: "Urbanisation, condo and villa development and a hot, humid climate are shaping demand for corrosion-resistant security doors and smart locks across Southeast Asia.",
    category: "Market Insight",
    date: "2026-04-15",
    dateLabel: "15 April 2026",
    readMins: 5,
    cover: `${BASE}images/gs-barbados.jpg`,
    excerpt: "Urbanisation, condo and villa development and a humid tropical climate are shaping demand for corrosion-resistant doors and smart locks across the region.",
    keywords: ["Southeast Asia security door market", "security door Vietnam Philippines", "condo smart lock Asia", "humid climate door"],
    body: [
      { type: "p", text: "Southeast Asia is one of the fastest-moving regions for residential security. For distributors, three characteristics make it a strong market for premium doors and smart locks." },
      { type: "h2", text: "Urbanisation and New-Build Housing" },
      { type: "p", text: "Rapid urban growth across Vietnam, the Philippines, Indonesia and neighbouring markets is producing waves of condominium and landed-housing projects, each of which needs entrance doors and locks at scale." },
      { type: "h2", text: "A Hot, Humid Climate" },
      { type: "p", text: "High humidity and coastal air make corrosion resistance essential. Cast-aluminium doors and well-sealed smart locks keep their finish and function far longer here than untreated steel or budget hardware." },
      { type: "h2", text: "Fast Smart-Home Adoption" },
      { type: "p", text: "The region is mobile-first and quick to adopt app-based living. Fingerprint and app locks are increasingly expected in new condos, which supports bundled sales across doors, locks and home devices." },
      { type: "h2", text: "The Opportunity" },
      { type: "p", text: "A climate-appropriate, smart-ready range positioned for mid-to-premium housing gives distributors room to grow on value rather than price. WONLY can supply and customise for local project requirements." },
      { type: "p", text: "Talk to our team about building a Southeast Asia range suited to your customers and climate." },
    ],
  },
  {
    slug: "security-door-ratings-and-certifications",
    title: "Understanding Security Door Ratings and Certifications for Import Markets",
    seoTitle: "Security Door Ratings & Protection Levels Explained | WONLY",
    description: "Security door ratings decoded — EN 1627 RC2–RC6 burglar-resistance classes, China GB 17565 grades and fire ratings, and how to choose the right protection level.",
    category: "Buying Guide",
    date: "2026-04-02",
    dateLabel: "2 April 2026",
    readMins: 7,
    cover: `${BASE}images/mfg-inspect.jpg`,
    excerpt: "EN 1627 RC2–RC6, GB 17565 grades and fire ratings decoded — what the classes mean and how to choose the right protection level for your market.",
    keywords: ["security door ratings", "EN 1627 RC2 RC3 RC4", "GB 17565 security door grade", "security door protection levels", "burglar resistance class"],
    body: [
      { type: "p", text: "When buyers compare security doors, one question comes up before price, finish or lead time: how secure is it, really? A rating only means something when it is independently tested. This guide explains the security-door ratings and protection levels that matter for importers, developers and project buyers." },
      { type: "h2", text: "Why Security Door Ratings Exist" },
      { type: "p", text: "A security-door rating is an independently tested measure of how long, and against which tools, a door resists forced entry — a class a test lab has verified, not a marketing claim. Two standards dominate international sourcing: EN 1627 (Europe and most export markets) and GB 17565 (China, where a large share of the world's security doors are made). Fire performance is rated separately." },
      { type: "h2", text: "EN 1627: Burglar-Resistance Classes RC2–RC6" },
      { type: "p", text: "EN 1627 is the European standard for the burglar resistance of doors and windows. It defines resistance classes RC1 to RC6, each set by the attacker profile, the tools allowed and the minimum time the door must hold:" },
      { type: "ul", items: ["RC2 — casual burglar with screwdriver and pliers, about 3 minutes: apartments and low-risk residential", "RC3 — experienced burglar adding a crowbar, about 5 minutes: villas and ground-floor homes", "RC4 — seasoned burglar with saw, hammer and cordless drill, about 10 minutes: high-value residential and light commercial", "RC5 — adds power tools, about 15 minutes: commercial and institutional", "RC6 — heavy power tools, about 20 minutes: banks, vaults and high-security sites"] },
      { type: "p", text: "For most residential export projects, RC2 to RC3 is the practical sweet spot; RC4 and above is specified for commercial, institutional and high-risk applications." },
      { type: "h2", text: "GB 17565: China's Security Door Grades" },
      { type: "p", text: "Because so many security doors are manufactured in China, buyers should also recognise GB 17565, China's technical standard for burglar-resistant doors. It classifies doors into grades — A, B, C and D — based on the net working time an attacker needs to break through, with Class A resisting the longest. A reputable China-based manufacturer can supply doors certified to both GB 17565 and EN 1627 — which is what international buyers should ask for." },
      { type: "h2", text: "Fire Ratings Are Separate" },
      { type: "p", text: "A door can be burglar-resistant and fire-rated, but these are two different tests. Fire performance is measured to EN 1634-1 (or UL 10C in North America) in minutes of integrity and insulation — 30, 60, 90 or 120 minutes. For hotels, hospitals, apartment corridors and public buildings, a fire rating of 60–90 minutes is usually mandatory alongside security." },
      { type: "h2", text: "Beyond the Class: What Makes a Door Hold" },
      { type: "ul", items: ["Lock and cylinder grade — the lock is the most-attacked point; anti-drill, anti-bump cylinders matter", "Multi-point locking — bolts engaging the frame at several points resist prying", "Frame and hinge strength — a strong leaf on a weak frame still fails", "Cycle testing — a quality door is tested to 200,000+ open/close cycles"] },
      { type: "h2", text: "How WONLY Doors Are Rated and Tested" },
      { type: "p", text: "WONLY has manufactured security doors since 1996 and is a listed company (SSE: 605268), backed by 1,000+ patents and 30 years with zero major safety incidents. Its security doors are independently tested against the standards above:" },
      { type: "ul", items: ["Class A — the highest China GB 17565 burglar-resistance grade", "EN 1634 fire-rated — 90-minute integrity, compliant with Gulf, SE Asia and Central Asia codes", "200,000+ open/close cycle tested, plus forced-entry testing", "Certified to ISO 9001, ISO 14001, CE, UL, CMA and CSPA", "Hurricane-rated (wind Class 12) and acoustic STC 35+ on applicable series"] },
      { type: "h2", text: "FAQ" },
      { type: "p", text: "What is the most common security door rating for homes? RC2 for apartments and RC3 for villas and ground-floor homes are the most widely specified residential classes." },
      { type: "p", text: "Can one door be both fire-rated and burglar-resistant? Yes — a well-engineered door can carry an EN 1627 burglar-resistance class and an EN 1634 fire rating at the same time." },
    ],
  },
  {
    slug: "africa-security-door-demand",
    title: "Africa's Growing Demand for Durable, Affordable Security Doors",
    seoTitle: "Africa Security Door Market — Durable & Affordable | WONLY",
    description: "Rapid construction, urban growth and a focus on value durability are driving African demand for steel and cast-aluminium security doors and reliable smart locks.",
    category: "Market Insight",
    date: "2026-03-19",
    dateLabel: "19 March 2026",
    readMins: 5,
    cover: `${BASE}images/gs-egypt-cbd.jpg`,
    excerpt: "Rapid construction, urban growth and a focus on durable value are driving African demand for security doors and reliable smart locks.",
    keywords: ["Africa security door market", "security door export Africa", "affordable security door", "door supplier Nigeria Kenya"],
    body: [
      { type: "p", text: "Across many African markets, a fast-growing middle class and steady construction are lifting demand for security doors that balance protection, durability and price. For exporters, the region rewards the right value proposition." },
      { type: "h2", text: "Construction and Urban Growth" },
      { type: "p", text: "New residential and commercial development in cities across the continent creates consistent demand for entrance doors, from value steel doors to premium cast-aluminium for higher-end projects." },
      { type: "h2", text: "Value and Durability Come First" },
      { type: "p", text: "Buyers prioritise doors that deliver dependable security and long service life for the price. A supplier who can offer strong steel value lines alongside premium options wins a wider share of projects." },
      { type: "h2", text: "The Rising Role of Smart Locks" },
      { type: "p", text: "As smartphone use spreads, interest in fingerprint and app locks is growing in urban and premium segments, adding an upsell path on top of the core door business." },
      { type: "h2", text: "The Opportunity for Distributors" },
      { type: "p", text: "A tiered range, reliable supply and clear after-sales support let distributors build trust and repeat business. WONLY manufactures at the scale and price points African markets need." },
      { type: "p", text: "Contact our team to discuss a product mix and pricing tailored to your African market." },
    ],
  },
];

export const getArticle = (slug: string): Article | undefined =>
  ARTICLES.find((a) => a.slug === slug);

export const relatedArticles = (slug: string, n = 3): Article[] =>
  ARTICLES.filter((a) => a.slug !== slug).slice(0, n);
