import type { Locale } from "./i18n";
import type { ProductPageData } from "./product-page";

type EntranceCopy = {
  seo: { title: string; description: string };
  eyebrow: string; title: string; sub: string; highlights: string[];
  seriesEyebrow: string; seriesTitle: string; series: { name: string; tag: string; description: string }[];
  featuresEyebrow: string; featuresTitle: string; features: { title: string; description: string }[];
  bandEyebrow: string; bandTitle: string; ctaTitle: string; ctaSub: string;
};

const ENTRANCE: Partial<Record<Locale, EntranceCopy>> = {
  ar: {
    seo: { title: "مصنّع أبواب مداخل أمنية وخشبية | WONLY", description: "أبواب مداخل WONLY تشمل أبواب أمان من الألمنيوم المصبوب وأبواباً داخلية هادئة من الفولاذ والخشب، مع تصنيع OEM/ODM للموزعين والمشاريع." },
    eyebrow: "أبواب المداخل", title: "الباب الذي يفتح كل الاحتمالات", sub: "من أبواب الأمان المصنوعة من الألمنيوم المصبوب إلى الأبواب الداخلية الهادئة، تصنع WONLY منظومة المدخل كاملة: حماية في الخارج وهدوء في الداخل.",
    highlights: ["أبواب أمان وداخلية من مصنع واحد", "مقاومة للحريق والسرقة وعازلة للصوت", "أكثر من 3 ملايين باب سنوياً من خطوطنا"],
    seriesEyebrow: "عائلتان من الأبواب", seriesTitle: "اختر مدخلك", series: [{ name: "أبواب الأمان", tag: "خارجي", description: "أبواب ألمنيوم مصبوب بقفل ذاتي واستشعار متعدد الاتجاهات لمحاولات الاقتحام." }, { name: "الأبواب الخشبية", tag: "داخلي", description: "أبواب هادئة من الفولاذ والخشب، مصممة لمقاومة الترهل والالتواء." }],
    featuresEyebrow: "هندسة متكاملة", featuresTitle: "حماية وهدوء وحرفية", features: [{ title: "أمان متعدد الاتجاهات", description: "مستشعرات تكتشف الكسر والخلع والحفر وفتح القفل وترسل تنبيهاً فورياً." }, { title: "مقاومة حريق 90 دقيقة", description: "أبواب خارجية وفق EN 1634 تحافظ على السلامة والعزل لمدة 90 دقيقة." }, { title: "قفل ذكي ذاتي", description: "قفل بيومتري مدعوم بالذكاء الاصطناعي مع تحكم بالتطبيق وحماية من العبث." }, { title: "عزل صوتي", description: "هياكل إحكام متدرجة وألواح سميكة لراحة هادئة داخل المبنى وخارجه." }, { title: "مقاومة للترهل والالتواء", description: "إطارات مدعمة بالفولاذ وألواح مزدوجة تحافظ على شكل الباب طوال عمره." }, { title: "صحة بيئية ENF", description: "أبواب داخلية دون غراء أو غبار ومتوافقة مع معيار ENF منخفض الفورمالديهايد." }],
    bandEyebrow: "تصنيع داخلي", bandTitle: "ملايين الأبواب سنوياً على خطوطنا الخاصة", ctaTitle: "أدخل أبواب WONLY إلى سوقك", ctaSub: "للأمان أو الداخل، للسكن أو المشروع: اطلب الكتالوج والعينات والأسعار.",
  },
  fr: {
    seo: { title: "Fabricant de portes d’entrée sécurisées et en bois | WONLY", description: "Les portes d’entrée WONLY réunissent portes de sécurité en aluminium moulé et portes intérieures silencieuses acier-bois, avec OEM/ODM pour distributeurs et projets." },
    eyebrow: "Portes d’entrée", title: "La porte qui ouvre toutes les possibilités", sub: "Des portes de sécurité en aluminium moulé aux portes intérieures silencieuses acier-bois, WONLY fabrique l’entrée complète : protection dehors, calme dedans.",
    highlights: ["Portes de sécurité et intérieures sous un même toit", "Résistance au feu, à l’effraction et isolation acoustique", "Plus de 3 millions de portes par an sur nos lignes"],
    seriesEyebrow: "Deux familles de portes", seriesTitle: "Choisissez votre entrée", series: [{ name: "Portes de sécurité", tag: "Extérieur", description: "Portes en aluminium moulé avec verrouillage autonome et détection multidirectionnelle des intrusions." }, { name: "Portes en bois", tag: "Intérieur", description: "Portes silencieuses acier-bois, conçues pour ne jamais s’affaisser ni se déformer." }],
    featuresEyebrow: "Conçu dès l’origine", featuresTitle: "Protection, silence et savoir-faire", features: [{ title: "Sécurité multidirectionnelle", description: "Des capteurs détectent forçage, levier, perçage et crochetage, puis alertent immédiatement." }, { title: "Résistance au feu 90 minutes", description: "Les portes extérieures EN 1634 conservent intégrité et isolation pendant 90 minutes." }, { title: "Verrouillage intelligent autonome", description: "Verrouillage biométrique piloté par IA, application mobile et architecture anti-sabotage." }, { title: "Isolation acoustique", description: "Joints étagés et vantaux épais assurent un calme de niveau hôtelier." }, { title: "Sans affaissement ni déformation", description: "Cadres renforcés en acier et vantaux à double ossature gardent leur forme durablement." }, { title: "Éco-santé ENF", description: "Portes intérieures sans colle ni poussière, conformes à la norme ENF sur le formaldéhyde." }],
    bandEyebrow: "Fabrication intégrée", bandTitle: "Des millions de portes par an sur nos propres lignes", ctaTitle: "Introduisez les portes WONLY sur votre marché", ctaSub: "Sécurité ou intérieur, résidentiel ou projet : demandez catalogue, échantillons et prix.",
  },
  ru: {
    seo: { title: "Производитель входных защитных и деревянных дверей | WONLY", description: "Входные двери WONLY: защитные двери из литого алюминия и тихие стально-деревянные межкомнатные двери. OEM/ODM для дистрибьюторов и проектов." },
    eyebrow: "Входные двери", title: "Дверь, открывающая все возможности", sub: "От защитных дверей из литого алюминия до тихих стально-деревянных дверей — WONLY производит весь входной комплекс: защита снаружи и тишина внутри.",
    highlights: ["Защитные и интерьерные двери на одном производстве", "Огнестойкость, защита от взлома и шумоизоляция", "Более 3 миллионов дверей в год на собственных линиях"],
    seriesEyebrow: "Две категории дверей", seriesTitle: "Выберите свой вход", series: [{ name: "Защитные двери", tag: "Наружные", description: "Двери из литого алюминия с автономным запиранием и многовекторным обнаружением вторжения." }, { name: "Деревянные двери", tag: "Интерьерные", description: "Тихие стально-деревянные двери, устойчивые к провисанию и деформации." }],
    featuresEyebrow: "Заложено конструкцией", featuresTitle: "Защита, тишина и мастерство", features: [{ title: "Многовекторная защита", description: "Датчики обнаруживают взлом, отжим, сверление и вскрытие замка и мгновенно оповещают." }, { title: "Огнестойкость 90 минут", description: "Наружные двери по EN 1634 сохраняют целостность и теплоизоляцию 90 минут." }, { title: "Автономное умное запирание", description: "Биометрический замок с ИИ, управлением через приложение и защитой от вмешательства." }, { title: "Шумоизоляция", description: "Ступенчатые уплотнения и толстые полотна обеспечивают тишину гостиничного уровня." }, { title: "Без провисания и деформации", description: "Стальные усиленные рамы и двойной каркас сохраняют форму двери весь срок службы." }, { title: "Экологичность ENF", description: "Межкомнатные двери без клея и пыли, соответствующие стандарту ENF по формальдегиду." }],
    bandEyebrow: "Собственное производство", bandTitle: "Миллионы дверей в год на собственных линиях", ctaTitle: "Выведите входные двери WONLY на свой рынок", ctaSub: "Защитные или интерьерные, жилые или проектные — запросите каталог, образцы и цены.",
  },
  es: {
    seo: { title: "Fabricante de puertas de entrada de seguridad y madera | WONLY", description: "Puertas de entrada WONLY: seguridad en aluminio fundido y puertas interiores silenciosas de acero y madera, con OEM/ODM para distribuidores y proyectos." },
    eyebrow: "Puertas de entrada", title: "La puerta que abre todas las posibilidades", sub: "Desde puertas de seguridad de aluminio fundido hasta puertas interiores silenciosas de acero y madera, WONLY fabrica toda la entrada: protección fuera y calma dentro.",
    highlights: ["Puertas de seguridad e interiores en una misma fábrica", "Resistencia al fuego, antirrobo y aislamiento acústico", "Más de 3 millones de puertas al año en líneas propias"],
    seriesEyebrow: "Dos familias de puertas", seriesTitle: "Elija su entrada", series: [{ name: "Puertas de seguridad", tag: "Exterior", description: "Puertas de aluminio fundido con cierre autónomo y detección multidireccional de intrusiones." }, { name: "Puertas de madera", tag: "Interior", description: "Puertas silenciosas de acero y madera, diseñadas para no ceder ni deformarse." }],
    featuresEyebrow: "Ingeniería integrada", featuresTitle: "Protección, silencio y artesanía", features: [{ title: "Seguridad multidireccional", description: "Sensores detectan fuerza, palanca, perforación y ganzuado y envían alertas inmediatas." }, { title: "Resistencia al fuego de 90 minutos", description: "Las puertas exteriores EN 1634 mantienen integridad y aislamiento durante 90 minutos." }, { title: "Cierre inteligente autónomo", description: "Cierre biométrico con IA, control por aplicación y arquitectura antisabotaje." }, { title: "Aislamiento acústico", description: "Sellos escalonados y hojas gruesas ofrecen silencio de nivel hotelero." }, { title: "Sin hundimiento ni deformación", description: "Marcos reforzados con acero y hojas de doble estructura conservan su forma." }, { title: "Salud ecológica ENF", description: "Puertas interiores sin cola ni polvo, conformes con el estándar ENF de formaldehído." }],
    bandEyebrow: "Fabricación propia", bandTitle: "Millones de puertas al año en nuestras propias líneas", ctaTitle: "Lleve las puertas WONLY a su mercado", ctaSub: "Seguridad o interior, residencial o proyecto: solicite catálogo, muestras y precios.",
  },
};

export function localizeEntranceDoor(data: ProductPageData, locale: Locale): ProductPageData {
  const c = ENTRANCE[locale];
  if (!c) return data;
  return {
    ...data,
    seo: { ...data.seo, ...c.seo },
    hero: { ...data.hero, eyebrow: c.eyebrow, title: c.title, sub: c.sub },
    highlights: c.highlights,
    seriesEyebrow: c.seriesEyebrow,
    seriesTitle: c.seriesTitle,
    series: data.series.map((item, index) => ({ ...item, name: c.series[index]?.name ?? item.name, tag: c.series[index]?.tag ?? item.tag, d: c.series[index]?.description ?? item.d })),
    featuresEyebrow: c.featuresEyebrow,
    featuresTitle: c.featuresTitle,
    features: data.features.map((item, index) => ({ ...item, t: c.features[index]?.title ?? item.t, d: c.features[index]?.description ?? item.d })),
    band: { ...data.band, eyebrow: c.bandEyebrow, title: c.bandTitle },
    cta: { title: c.ctaTitle, sub: c.ctaSub },
  };
}

const SECURITY_TEXT: Partial<Record<Locale, Record<string, string>>> = {
  ar: {
    "SEO Title": "مصنّع أبواب أمان وأبواب مقاومة للحريق | WONLY", "SEO Description": "WONLY مصنّع ومورّد OEM/ODM لأبواب الأمان: أبواب روبوتية وأبواب EN 1634 مقاومة للحريق 90 دقيقة وأبواب طبية وفاخرة للموزعين والمشاريع.",
    "Security Doors · Since 1996": "أبواب أمان · منذ 1996", "Engineered to": "مصممة من أجل", "defend": "حماية", "every entry": "كل مدخل", "Hero Description": "من الأبواب الروبوتية الرائدة إلى سلاسل المشاريع المقاومة للحريق، حماية معتمدة وجاهزة للمشاريع السكنية والتجارية والمؤسسية حول العالم.", "View the Range": "عرض المجموعة",
    "The Range": "المجموعة", "Six Series. Every Grade And Scenario": "ست سلاسل لكل درجة وكل سيناريو", "Range Description": "تغطي درجات الأمان ومقاومة الحريق والتطبيقات المختلفة، بدعم أكثر من 1,000 براءة اختراع و30 عاماً من الهندسة.", "Core Technology": "التقنية الأساسية", "Six Layers Of Defense, In Every Door": "ست طبقات دفاع في كل باب", "Tested to Destruction": "اختبارات حتى أقصى الحدود", "Certified In Our Own Labs Before It Ships": "يُعتمد في مختبراتنا قبل الشحن", Specifications: "المواصفات", "Technical Excellence, To Spec": "تفوق تقني وفق المواصفات", Applications: "التطبيقات", "Built For Every Space": "مصمم لكل مساحة", "Held To The Highest Security Standards": "ملتزم بأعلى معايير الأمان",
    Years: "سنوات", "Fire Rating": "مقاومة الحريق", "Cycle Test": "اختبار الدورات", "Class Grade": "درجة التصنيف", "Security Grade": "درجة الأمان", Material: "المادة", "Lock System": "نظام القفل", "Door Thickness": "سماكة الباب", "Acoustic Rating": "تصنيف العزل الصوتي", "Wind Resistance": "مقاومة الرياح", Certifications: "الشهادات", "Spec Description": "كل معلمة تلبي أو تتجاوز معايير الأمان الدولية، مع تكوينات مخصصة لمتطلبات المشاريع.", "Request Full Spec Sheet": "اطلب ورقة المواصفات الكاملة", "Ready to Secure Your Project?": "هل مشروعك جاهز للحماية؟", "Custom Security-Door Solutions & Pricing": "حلول وأسعار أبواب أمان مخصصة", "CTA Description": "يرد فريقنا الهندسي خلال 24 ساعة بالمواصفات ووثائق المطابقة وأسعار المشروع.",
  },
  fr: {
    "SEO Title": "Fabricant de portes de sécurité et coupe-feu | WONLY", "SEO Description": "WONLY fabrique des portes de sécurité OEM/ODM : modèles robotisés, portes EN 1634 coupe-feu 90 minutes, médicales et haut de gamme pour distributeurs et projets.",
    "Security Doors · Since 1996": "Portes de sécurité · Depuis 1996", "Engineered to": "Conçues pour", defend: "défendre", "every entry": "chaque entrée", "Hero Description": "Des portes robotisées phares aux séries techniques coupe-feu, une sécurité certifiée et prête pour les projets résidentiels, commerciaux et institutionnels.", "View the Range": "Voir la gamme",
    "The Range": "La gamme", "Six Series. Every Grade And Scenario": "Six séries pour chaque niveau et chaque usage", "Range Description": "Toutes les classes de sécurité, résistances au feu et applications, soutenues par plus de 1 000 brevets et 30 ans d’ingénierie.", "Core Technology": "Technologie centrale", "Six Layers Of Defense, In Every Door": "Six couches de défense dans chaque porte", "Tested to Destruction": "Testé jusqu’aux limites", "Certified In Our Own Labs Before It Ships": "Certifié dans nos laboratoires avant expédition", Specifications: "Spécifications", "Technical Excellence, To Spec": "Excellence technique conforme au cahier des charges", Applications: "Applications", "Built For Every Space": "Conçu pour chaque espace", "Held To The Highest Security Standards": "Conforme aux normes de sécurité les plus élevées",
    Years: "Années", "Fire Rating": "Résistance au feu", "Cycle Test": "Essai de cycles", "Class Grade": "Classe", "Security Grade": "Niveau de sécurité", Material: "Matériau", "Lock System": "Système de serrure", "Door Thickness": "Épaisseur de porte", "Acoustic Rating": "Performance acoustique", "Wind Resistance": "Résistance au vent", Certifications: "Certifications", "Spec Description": "Chaque paramètre satisfait ou dépasse les normes internationales, avec configurations sur mesure pour les projets.", "Request Full Spec Sheet": "Demander la fiche technique", "Ready to Secure Your Project?": "Prêt à sécuriser votre projet ?", "Custom Security-Door Solutions & Pricing": "Solutions et prix de portes de sécurité sur mesure", "CTA Description": "Notre équipe technique répond sous 24 heures avec spécifications, conformité et prix projet.",
  },
  ru: {
    "SEO Title": "Производитель защитных и противопожарных дверей | WONLY", "SEO Description": "WONLY производит защитные двери OEM/ODM: роботизированные модели, двери EN 1634 с огнестойкостью 90 минут, медицинские и премиальные серии для проектов.",
    "Security Doors · Since 1996": "Защитные двери · С 1996 года", "Engineered to": "Созданы, чтобы", defend: "защищать", "every entry": "каждый вход", "Hero Description": "От флагманских роботизированных дверей до противопожарных инженерных серий — сертифицированная защита для жилых, коммерческих и общественных проектов.", "View the Range": "Смотреть серии",
    "The Range": "Модельный ряд", "Six Series. Every Grade And Scenario": "Шесть серий для каждого класса и сценария", "Range Description": "Все классы безопасности, показатели огнестойкости и области применения — более 1 000 патентов и 30 лет инженерного опыта.", "Core Technology": "Ключевые технологии", "Six Layers Of Defense, In Every Door": "Шесть уровней защиты в каждой двери", "Tested to Destruction": "Испытано на пределе", "Certified In Our Own Labs Before It Ships": "Сертификация в собственных лабораториях до отгрузки", Specifications: "Характеристики", "Technical Excellence, To Spec": "Техническое совершенство по спецификации", Applications: "Применение", "Built For Every Space": "Для каждого пространства", "Held To The Highest Security Standards": "Соответствие высшим стандартам безопасности",
    Years: "Лет", "Fire Rating": "Огнестойкость", "Cycle Test": "Циклические испытания", "Class Grade": "Класс", "Security Grade": "Класс безопасности", Material: "Материал", "Lock System": "Система замка", "Door Thickness": "Толщина двери", "Acoustic Rating": "Звукоизоляция", "Wind Resistance": "Ветровая нагрузка", Certifications: "Сертификаты", "Spec Description": "Все параметры соответствуют или превосходят международные нормы; доступны конфигурации под требования проекта.", "Request Full Spec Sheet": "Запросить полную спецификацию", "Ready to Secure Your Project?": "Готовы защитить свой проект?", "Custom Security-Door Solutions & Pricing": "Индивидуальные решения и цены на защитные двери", "CTA Description": "Инженерная команда ответит в течение 24 часов и подготовит спецификации, документы и проектные цены.",
  },
  es: {
    "SEO Title": "Fabricante de puertas de seguridad y cortafuego | WONLY", "SEO Description": "WONLY fabrica puertas de seguridad OEM/ODM: modelos robotizados, puertas EN 1634 resistentes al fuego 90 minutos, médicas y de lujo para distribuidores y proyectos.",
    "Security Doors · Since 1996": "Puertas de seguridad · Desde 1996", "Engineered to": "Diseñadas para", defend: "proteger", "every entry": "cada entrada", "Hero Description": "Desde puertas robotizadas insignia hasta series técnicas cortafuego, seguridad certificada para proyectos residenciales, comerciales e institucionales.", "View the Range": "Ver la gama",
    "The Range": "La gama", "Six Series. Every Grade And Scenario": "Seis series para cada nivel y escenario", "Range Description": "Todos los grados de seguridad, resistencias al fuego y aplicaciones, respaldados por más de 1.000 patentes y 30 años de ingeniería.", "Core Technology": "Tecnología central", "Six Layers Of Defense, In Every Door": "Seis capas de defensa en cada puerta", "Tested to Destruction": "Probado hasta el límite", "Certified In Our Own Labs Before It Ships": "Certificado en nuestros laboratorios antes del envío", Specifications: "Especificaciones", "Technical Excellence, To Spec": "Excelencia técnica según especificación", Applications: "Aplicaciones", "Built For Every Space": "Diseñado para cada espacio", "Held To The Highest Security Standards": "Conforme con los estándares de seguridad más exigentes",
    Years: "Años", "Fire Rating": "Resistencia al fuego", "Cycle Test": "Prueba de ciclos", "Class Grade": "Clase", "Security Grade": "Grado de seguridad", Material: "Material", "Lock System": "Sistema de cierre", "Door Thickness": "Espesor de puerta", "Acoustic Rating": "Clasificación acústica", "Wind Resistance": "Resistencia al viento", Certifications: "Certificaciones", "Spec Description": "Cada parámetro cumple o supera las normas internacionales, con configuraciones personalizadas para cada proyecto.", "Request Full Spec Sheet": "Solicitar ficha técnica completa", "Ready to Secure Your Project?": "¿Listo para proteger su proyecto?", "Custom Security-Door Solutions & Pricing": "Soluciones y precios de puertas de seguridad a medida", "CTA Description": "Nuestro equipo técnico responde en 24 horas con especificaciones, documentación y precios de proyecto.",
  },
};

export function securityDoorText(locale: Locale, text: string): string {
  return SECURITY_TEXT[locale]?.[text] ?? text;
}

type SecurityItem = { title: string; tag?: string; description: string };
const SECURITY_SERIES: Partial<Record<Locale, SecurityItem[]>> = {
  ar: [
    { title: "باب الأمان الروبوتي X70", tag: "الرائد", description: "قفل ذاتي واستشعار متعدد الاتجاهات وهيكل فاخر من الألمنيوم المصبوب للفلل والمساكن الراقية." }, { title: "سلسلة 4.0 العالمية", tag: "الأكثر مبيعاً", description: "نماذج عالمية مقاومة للحريق والسرقة ومهيأة للمناخات المختلفة." }, { title: "الباب الروبوتي K300 Pro", tag: "ذكي", description: "دخول بالذكاء الاصطناعي والتعرف على الوجه وإدارة عبر التطبيق للمساكن الحديثة." }, { title: "أبواب المشاريع المقاومة للحريق", tag: "مقاوم للحريق", description: "مطابقة EN 1634 بسلامة لمدة 90 دقيقة لمتطلبات الخليج وآسيا." }, { title: "أبواب طبية", tag: "طبي", description: "أبواب محكمة لغرف العمليات والأجنحة في المستشفيات والبيئات النظيفة." }, { title: "YIZHAI YISHU الحرفية", tag: "فاخر", description: "أبواب فلل مخصصة تجمع فن التراث مع الحماية والدخول الذكي." },
  ],
  fr: [
    { title: "Porte de sécurité robotisée X70", tag: "Phare", description: "Verrouillage autonome, détection multidirectionnelle et aluminium moulé haut de gamme pour villas et résidences." }, { title: "Série mondiale 4.0", tag: "Meilleure vente", description: "Modèles universels coupe-feu, anti-effraction et adaptés aux différents climats." }, { title: "Porte robotisée K300 Pro", tag: "Intelligente", description: "Accès par IA, reconnaissance faciale et gestion mobile pour les logements de nouvelle génération." }, { title: "Portes coupe-feu techniques", tag: "Coupe-feu", description: "Conformes EN 1634 avec intégrité 90 minutes pour les codes du Golfe et d’Asie." }, { title: "Portes de qualité médicale", tag: "Médical", description: "Portes hermétiques pour blocs opératoires, chambres et environnements propres." }, { title: "YIZHAI YISHU artisanale", tag: "Luxe", description: "Portes de villa sur mesure où protection, art patrimonial et accès intelligent se rencontrent." },
  ],
  ru: [
    { title: "Роботизированная защитная дверь X70", tag: "Флагман", description: "Автономное запирание, многовекторные датчики и литой алюминий для вилл и премиальных резиденций." }, { title: "Глобальная серия 4.0", tag: "Хит продаж", description: "Универсальные модели с огнестойкостью, защитой от взлома и климатической адаптацией." }, { title: "Роботизированная дверь K300 Pro", tag: "Умная", description: "ИИ, распознавание лица и управление приложением для современного жилья." }, { title: "Инженерные противопожарные двери", tag: "Огнестойкие", description: "EN 1634 и целостность 90 минут для норм стран Персидского залива и Азии." }, { title: "Медицинские двери", tag: "Медицина", description: "Герметичные двери операционных, палат и чистых помещений." }, { title: "Авторская серия YIZHAI YISHU", tag: "Люкс", description: "Индивидуальные двери для вилл, объединяющие защиту, искусство и умный доступ." },
  ],
  es: [
    { title: "Puerta de seguridad robotizada X70", tag: "Insignia", description: "Cierre autónomo, detección multidireccional y aluminio fundido prémium para villas y residencias." }, { title: "Serie Global 4.0", tag: "Más vendida", description: "Modelos universales cortafuego, antirrobo y adaptados a distintos climas." }, { title: "Puerta robotizada K300 Pro", tag: "Inteligente", description: "Acceso con IA, reconocimiento facial y gestión por aplicación para viviendas modernas." }, { title: "Puertas técnicas cortafuego", tag: "Cortafuego", description: "EN 1634 con integridad de 90 minutos para normativas del Golfo y Asia." }, { title: "Puertas de grado médico", tag: "Médico", description: "Puertas herméticas para quirófanos, habitaciones y entornos limpios." }, { title: "YIZHAI YISHU artesanal", tag: "Lujo", description: "Puertas a medida para villas que unen protección, arte tradicional y acceso inteligente." },
  ],
};

const SECURITY_FEATURES: Partial<Record<Locale, SecurityItem[]>> = {
  ar: [{ title: "استشعار اقتحام متعدد الاتجاهات", description: "يكشف الكسر والخلع والحفر وفتح القفل ويرسل تنبيهات فورية." }, { title: "مقاومة حريق 90 دقيقة", description: "اعتماد EN 1634 للحفاظ على الثبات والعزل لمدة 90 دقيقة." }, { title: "قفل ذكي ذاتي", description: "مصادقة بيومترية وتحكم بالتطبيق وهيكل مقاوم للعبث." }, { title: "هندسة ملائمة للمناخ", description: "مقاومة للأعاصير والتآكل وعزل حراري للمناخات القاسية." }, { title: "عزل صوتي", description: "نواة عازلة وإحكام دقيق يوفران تصنيف STC 35+." }, { title: "تحمل 200,000 دورة", description: "اختبار فتح وإغلاق 200,000 مرة لضمان الاعتمادية طويلة الأمد." }],
  fr: [{ title: "Détection d’intrusion multidirectionnelle", description: "Détecte forçage, levier, perçage et crochetage avec alerte immédiate." }, { title: "Résistance au feu 90 minutes", description: "Certification EN 1634 avec stabilité et isolation pendant 90 minutes." }, { title: "Verrouillage intelligent autonome", description: "Authentification biométrique, application et architecture anti-sabotage." }, { title: "Ingénierie adaptée au climat", description: "Résistance aux ouragans, à la corrosion et rupture thermique pour climats sévères." }, { title: "Isolation acoustique", description: "Âmes absorbantes et joints précis pour une performance STC 35+." }, { title: "Durabilité 200 000 cycles", description: "Essais de 200 000 ouvertures-fermetures pour une fiabilité durable." }],
  ru: [{ title: "Многовекторное обнаружение вторжения", description: "Обнаруживает взлом, отжим, сверление и вскрытие с мгновенным оповещением." }, { title: "Огнестойкость 90 минут", description: "EN 1634: сохранение устойчивости и теплоизоляции 90 минут." }, { title: "Автономное умное запирание", description: "Биометрия, управление приложением и защита от вмешательства." }, { title: "Климатическая адаптация", description: "Ураганостойкость, защита от коррозии и терморазрыв для сурового климата." }, { title: "Шумоизоляция", description: "Звукопоглощающий наполнитель и точные уплотнения обеспечивают STC 35+." }, { title: "Ресурс 200 000 циклов", description: "Испытания на 200 000 открываний и закрываний подтверждают долговечность." }],
  es: [{ title: "Detección multidireccional de intrusión", description: "Detecta fuerza, palanca, perforación y ganzuado con alertas inmediatas." }, { title: "Resistencia al fuego 90 minutos", description: "EN 1634 con estabilidad y aislamiento durante 90 minutos." }, { title: "Cierre inteligente autónomo", description: "Biometría, control por aplicación y arquitectura antisabotaje." }, { title: "Ingeniería adaptada al clima", description: "Resistencia a huracanes, corrosión y rotura térmica para climas extremos." }, { title: "Aislamiento acústico", description: "Núcleos fonoabsorbentes y sellado preciso para STC 35+." }, { title: "Durabilidad de 200.000 ciclos", description: "Pruebas de 200.000 aperturas y cierres para fiabilidad a largo plazo." }],
};

const SECURITY_APPLICATIONS: Partial<Record<Locale, SecurityItem[]>> = {
  ar: [{ title: "فلل ومساكن فاخرة", description: "تصاميم مخصصة بأعلى درجات الأمان وتكامل مع المنزل الذكي." }, { title: "تجاري وشركات", description: "للبنوك ومراكز البيانات والمقار مع مقاومة الاقتحام ومتطلبات سلامة الأرواح." }, { title: "مؤسسات طبية وعامة", description: "أبواب غرف عمليات وأجنحة ومداخل مضبوطة للمستشفيات والمرافق الحكومية." }],
  fr: [{ title: "Villas et résidences haut de gamme", description: "Créations sur mesure, sécurité élevée et intégration à la maison intelligente." }, { title: "Bâtiments commerciaux et sièges", description: "Banques, centres de données et sièges protégés contre l’effraction et conformes à la sécurité incendie." }, { title: "Établissements médicaux et publics", description: "Blocs opératoires, chambres et accès contrôlés pour hôpitaux et bâtiments publics." }],
  ru: [{ title: "Премиальные виллы и резиденции", description: "Индивидуальный дизайн, высокий класс защиты и интеграция с умным домом." }, { title: "Коммерческие и корпоративные объекты", description: "Банки, дата-центры и офисы с защитой от взлома и соблюдением норм безопасности." }, { title: "Медицинские и общественные учреждения", description: "Операционные, палаты и контролируемые входы для больниц и госучреждений." }],
  es: [{ title: "Villas y residencias prémium", description: "Diseños a medida, seguridad de alto nivel e integración con hogar inteligente." }, { title: "Edificios comerciales y corporativos", description: "Bancos, centros de datos y sedes con protección antirrobo y cumplimiento de seguridad." }, { title: "Instituciones médicas y públicas", description: "Quirófanos, habitaciones y accesos controlados para hospitales y edificios públicos." }],
};

function localizedSecurityItem(source: Partial<Record<Locale, SecurityItem[]>>, locale: Locale, index: number, fallback: SecurityItem): SecurityItem { return source[locale]?.[index] ?? fallback; }
export const securitySeries = (locale: Locale, index: number, fallback: SecurityItem) => localizedSecurityItem(SECURITY_SERIES, locale, index, fallback);
export const securityFeature = (locale: Locale, index: number, fallback: SecurityItem) => localizedSecurityItem(SECURITY_FEATURES, locale, index, fallback);
export const securityApplication = (locale: Locale, index: number, fallback: SecurityItem) => localizedSecurityItem(SECURITY_APPLICATIONS, locale, index, fallback);

type WoodenCopy = Omit<EntranceCopy, "series"> & { series: { name: string; tag: string; description: string }[] };
const WOODEN: Partial<Record<Locale, WoodenCopy>> = {
  ar: {
    seo: { title: "مصنّع أبواب خشبية هادئة مقاومة للالتواء | WONLY", description: "أبواب WONLY الفولاذية الخشبية توفر عزلاً صوتياً وهيكلاً مزدوجاً مقاومًا للترهل والرطوبة، ومتوافقة مع ENF وخدمات OEM/ODM." }, eyebrow: "أبواب خشبية", title: "أبواب فولاذية خشبية هادئة", sub: "هدوء مضاعف وهندسة مقاومة للالتواء، تجمع الحرفية مع قلب مدعم بالفولاذ للمساكن والمشاريع والتصاميم الخاصة.", highlights: ["باب واحد بأثر عزل بابين", "بناء ENF منخفض الفورمالديهايد", "مقاوم للترهل والالتواء والرطوبة"], seriesEyebrow: "مجموعة الأبواب الخشبية", seriesTitle: "حرفة واحدة، سلاسل متعددة", series: [{ name: "باب فولاذي خشبي هادئ", tag: "الرائد", description: "لوح مزدوج وإطار فولاذي مجلفن لمعيار جديد في الهدوء ومقاومة الالتواء." }, { name: "باب خشبي بيئي ENF", tag: "منخفض الفورمالديهايد", description: "متوافق مع ENF، دون غراء أو غبار، لمساحات داخلية صحية." }, { name: "باب YIZHAI الفني", tag: "فاخر", description: "ألواح حرفية مخصصة تحول الديكور الداخلي إلى فن متوارث." }], featuresEyebrow: "هندسة متكاملة", featuresTitle: "هدوء وصلابة وعمر طويل", features: [{ title: "هدوء مضاعف", description: "هيكل إحكام متدرج رباعي الجوانب يمنع الضوضاء والدخان والغبار والحشرات." }, { title: "أمان أكبر", description: "إطار فولاذي ومزلاج متصلان بصلابة لمقاومة الاقتحام العنيف." }, { title: "لا ترهل أو التواء", description: "لوح مزدوج وإطار مدعم بالفولاذ المجلفن يحافظان على الشكل." }, { title: "مقاوم للرطوبة", description: "ربط الفولاذ والخشب يعزل الخشب عن الجدار والرطوبة." }, { title: "خصوصية أعلى", description: "لوح بسماكة 6 سم يوفر خصوصية صوتية بمستوى فندق خمس نجوم." }, { title: "بيئي وصحي", description: "دون نشر أو غراء أو غبار أو فورمالديهايد، وفق معيار ENF." }], bandEyebrow: "حرفية على نطاق واسع", bandTitle: "3 ملايين باب خشبي سنوياً من خطوطنا", ctaTitle: "أدخل أبواب WONLY الخشبية إلى سوقك", ctaSub: "للسكن أو التجارة أو التصميم الخاص، اطلب الكتالوج والعينات والأسعار." },
  fr: {
    seo: { title: "Fabricant de portes bois silencieuses anti-déformation | WONLY", description: "Portes acier-bois WONLY : isolation acoustique, double ossature anti-déformation, résistance à l’humidité et conformité ENF, avec services OEM/ODM." }, eyebrow: "Portes en bois", title: "Portes silencieuses acier-bois", sub: "Deux fois plus de silence, sans déformation : le savoir-faire du bois associé à un cœur renforcé d’acier pour résidentiel, tertiaire et sur-mesure.", highlights: ["Une porte, l’effet acoustique de deux", "Construction ENF à très faibles émissions", "Sans affaissement, déformation ni crainte de l’humidité"], seriesEyebrow: "Gamme de portes bois", seriesTitle: "Un savoir-faire, plusieurs séries", series: [{ name: "Porte silencieuse acier-bois", tag: "Phare", description: "Vantail double ossature et cadre acier galvanisé, référence du silence et de la stabilité." }, { name: "Porte bois écologique ENF", tag: "Très faibles émissions", description: "Conforme ENF, sans colle ni poussière, pour des intérieurs sains." }, { name: "Porte artistique YIZHAI", tag: "Luxe", description: "Vantaux artisanaux sur mesure où la décoration intérieure devient art patrimonial." }], featuresEyebrow: "Conçu dès l’origine", featuresTitle: "Silencieux, solide et durable", features: [{ title: "Double silence", description: "Un joint étagé breveté sur quatre côtés bloque bruit, fumée, poussière et insectes." }, { title: "Sécurité renforcée", description: "Cadre acier et verrou s’assemblent rigidement pour résister aux effractions violentes." }, { title: "Sans affaissement ni déformation", description: "Double ossature et cadre renforcé en acier galvanisé conservent leur forme." }, { title: "Résistant à l’humidité", description: "La liaison acier-bois isole le bois du mur et de l’humidité." }, { title: "Plus d’intimité", description: "Un vantail de 6 cm offre une confidentialité acoustique de niveau hôtel cinq étoiles." }, { title: "Écologique et sain", description: "Sans sciage, colle, poussière ni formaldéhyde, conformément à la norme ENF." }], bandEyebrow: "Artisanat à grande échelle", bandTitle: "3 millions de portes bois par an, fabriquées en interne", ctaTitle: "Introduisez les portes bois WONLY sur votre marché", ctaSub: "Résidentiel, tertiaire ou sur-mesure : demandez catalogue, échantillons et prix." },
  ru: {
    seo: { title: "Производитель тихих деревянных дверей без деформации | WONLY", description: "Стально-деревянные двери WONLY: шумоизоляция, двойной каркас без провисания, влагостойкость и соответствие ENF. OEM/ODM для дистрибьюторов." }, eyebrow: "Деревянные двери", title: "Тихие стально-деревянные двери", sub: "Двойная тишина без деформации: мастерство работы с деревом и усиленный стальной сердечник для жилых, коммерческих и индивидуальных интерьеров.", highlights: ["Одна дверь с эффектом двух", "Конструкция ENF с минимальными выбросами", "Без провисания, деформации и боязни влаги"], seriesEyebrow: "Линейка деревянных дверей", seriesTitle: "Одно мастерство, несколько серий", series: [{ name: "Тихая стально-деревянная дверь", tag: "Флагман", description: "Двойной каркас полотна и оцинкованная стальная рама — эталон тишины и стабильности." }, { name: "Экологичная дверь ENF", tag: "Без формальдегида", description: "Соответствие ENF, без клея и пыли, для здорового интерьера." }, { name: "Художественная дверь YIZHAI", tag: "Люкс", description: "Индивидуальные авторские полотна, превращающие интерьер в наследное искусство." }], featuresEyebrow: "Заложено конструкцией", featuresTitle: "Тишина, прочность и долговечность", features: [{ title: "Двойная тишина", description: "Запатентованное четырёхстороннее ступенчатое уплотнение блокирует шум, дым, пыль и насекомых." }, { title: "Больше безопасности", description: "Стальная рама и ригель жёстко соединяются и сопротивляются силовому взлому." }, { title: "Без провисания и деформации", description: "Двойной каркас и оцинкованная стальная рама сохраняют форму." }, { title: "Влагостойкость", description: "Соединение стали и дерева изолирует древесину от стены и сырости." }, { title: "Больше приватности", description: "Полотно толщиной 6 см обеспечивает тишину уровня пятизвёздочного отеля." }, { title: "Экологичность и здоровье", description: "Без распила, клея, пыли и формальдегида, по стандарту ENF." }], bandEyebrow: "Мастерство в масштабе", bandTitle: "3 миллиона деревянных дверей в год на собственном производстве", ctaTitle: "Выведите деревянные двери WONLY на свой рынок", ctaSub: "Жилые, коммерческие или индивидуальные решения — запросите каталог, образцы и цены." },
  es: {
    seo: { title: "Fabricante de puertas de madera silenciosas y antideformación | WONLY", description: "Puertas de acero y madera WONLY: aislamiento acústico, doble estructura antideformación, resistencia a humedad y conformidad ENF, con OEM/ODM." }, eyebrow: "Puertas de madera", title: "Puertas silenciosas de acero y madera", sub: "El doble de silencio sin deformación: artesanía en madera y núcleo reforzado de acero para interiores residenciales, comerciales y a medida.", highlights: ["Una puerta con el efecto acústico de dos", "Construcción ENF de muy bajas emisiones", "No cede, no se deforma y resiste la humedad"], seriesEyebrow: "Gama de puertas de madera", seriesTitle: "Una artesanía, varias series", series: [{ name: "Puerta silenciosa de acero y madera", tag: "Insignia", description: "Hoja de doble estructura y marco de acero galvanizado, referencia en silencio y estabilidad." }, { name: "Puerta ecológica ENF", tag: "Bajas emisiones", description: "Conforme con ENF, sin cola ni polvo, para interiores saludables." }, { name: "Puerta artística YIZHAI", tag: "Lujo", description: "Hojas artesanales a medida que convierten el interior en arte patrimonial." }], featuresEyebrow: "Ingeniería integrada", featuresTitle: "Silencio, solidez y larga vida", features: [{ title: "Doble silencio", description: "Un sello escalonado patentado en cuatro lados bloquea ruido, humo, polvo e insectos." }, { title: "Mayor seguridad", description: "Marco de acero y cerrojo se unen rígidamente para resistir entradas forzadas." }, { title: "Sin hundimiento ni deformación", description: "La doble estructura y el acero galvanizado conservan la forma." }, { title: "Resistente a la humedad", description: "La unión acero-madera separa la madera del muro y la humedad." }, { title: "Mayor privacidad", description: "Una hoja de 6 cm ofrece privacidad acústica de hotel cinco estrellas." }, { title: "Ecológica y saludable", description: "Sin serrado, cola, polvo ni formaldehído, conforme con ENF." }], bandEyebrow: "Artesanía a escala", bandTitle: "3 millones de puertas de madera al año, fabricadas internamente", ctaTitle: "Lleve las puertas de madera WONLY a su mercado", ctaSub: "Residencial, comercial o a medida: solicite catálogo, muestras y precios." },
};

export function localizeWoodenDoor(data: ProductPageData, locale: Locale): ProductPageData {
  const c = WOODEN[locale]; if (!c) return data;
  return { ...data, seo: { ...data.seo, ...c.seo }, hero: { ...data.hero, eyebrow: c.eyebrow, title: c.title, sub: c.sub }, highlights: c.highlights, seriesEyebrow: c.seriesEyebrow, seriesTitle: c.seriesTitle, series: data.series.map((item, i) => ({ ...item, name: c.series[i]?.name ?? item.name, tag: c.series[i]?.tag ?? item.tag, d: c.series[i]?.description ?? item.d })), featuresEyebrow: c.featuresEyebrow, featuresTitle: c.featuresTitle, features: data.features.map((item, i) => ({ ...item, t: c.features[i]?.title ?? item.t, d: c.features[i]?.description ?? item.d })), band: { ...data.band, eyebrow: c.bandEyebrow, title: c.bandTitle }, cta: { title: c.ctaTitle, sub: c.ctaSub } };
}

const SMART_LOCK: Partial<Record<Locale, WoodenCopy>> = {
  ar: { seo: { title: "مصنّع أقفال ذكية وبصمة وبيومترية | WONLY", description: "أقفال WONLY الذكية للموزعين والمشاريع: دخول دون لمس، بصمة وكف، حراسة فيديو، تحكم بالتطبيق واتصال مشفر مقاوم للعبث." }, eyebrow: "أقفال ذكية", title: "دخول ذكي دون لمس", sub: "استشعار بعيد يفتح عند الاقتراب، ومصادقة بيومترية وأمان مشفر مقاوم للعبث؛ القلب الذكي لباب WONLY.", highlights: ["استشعار بعيد دون لمس", "بصمة كف وإصبع", "تصميم مشفر مقاوم للعبث"], seriesEyebrow: "مجموعة الأقفال", seriesTitle: "قفل لكل باب", series: [{ name: "قفل S80 True-Sensing", tag: "الرائد", description: "استشعار بعيد دون لمس مع القياسات الحيوية والتحكم بالتطبيق." }, { name: "قفل دفع وسحب ببصمة الكف", tag: "بيومتري", description: "تعرف دون لمس على أوردة الكف ومقبض دفع وسحب بحركة واحدة." }, { name: "قفل ذكي بحراسة فيديو", tag: "مع كاميرا", description: "كاميرا وتنبيهات حركة تنقل صورة الزوار إلى الهاتف." }, { name: "نظام دخول تجاري", tag: "مؤسسات", description: "RFID ورمز PIN وتطبيق للمكاتب والفنادق والمباني العامة." }], featuresEyebrow: "هندسة متكاملة", featuresTitle: "أمان يعمل دون تفكير", features: [{ title: "دخول True-Sensing", description: "يتعرف الاستشعار بعيد المدى عليك ويفتح دون لمس عند الاقتراب." }, { title: "قياسات حيوية متعددة", description: "أوردة الكف والبصمة والرمز والبطاقة والتطبيق حتى ست طرق للفتح." }, { title: "حراسة فيديو", description: "كاميرا مدمجة مع كشف الحركة تنقل الزوار إلى هاتفك." }, { title: "تطبيق ومشاهد ذكية", description: "فتح عن بعد وكلمات مرور مؤقتة وربط بمشاهد المنزل الذكي." }, { title: "مقاوم للعبث", description: "اتصال مشفر وهيكل مقاوم للخلع والحفر." }, { title: "تسليح وإلغاء تلقائي", description: "يسلح المنزل عند المغادرة ويلغي الحماية عند العودة." }], bandEyebrow: "تصنيع داخلي", bandTitle: "ملايين الأقفال الذكية سنوياً على خطوطنا", ctaTitle: "أدخل أقفال WONLY الذكية إلى سوقك", ctaSub: "للسكن أو الضيافة أو التجارة، اطلب الكتالوج والعينات والأسعار." },
  fr: { seo: { title: "Fabricant de serrures intelligentes biométriques | WONLY", description: "Serrures intelligentes WONLY : accès mains libres, veines de la paume, empreinte, vidéo, application et sécurité chiffrée anti-sabotage pour distributeurs et projets." }, eyebrow: "Serrures intelligentes", title: "Accès mains libres à détection réelle", sub: "Détection longue portée, biométrie et sécurité chiffrée anti-sabotage : le cœur intelligent de la porte WONLY.", highlights: ["Détection longue portée mains libres", "Biométrie paume et empreinte", "Conception chiffrée anti-sabotage"], seriesEyebrow: "Gamme de serrures", seriesTitle: "Une serrure pour chaque porte", series: [{ name: "Serrure S80 True-Sensing", tag: "Phare", description: "Détection longue portée mains libres, biométrie et contrôle par application." }, { name: "Serrure push-pull à veines de la paume", tag: "Biométrique", description: "Reconnaissance sans contact de la paume et poignée push-pull en un geste." }, { name: "Serrure intelligente Video Guard", tag: "Avec caméra", description: "Caméra intégrée et alertes de mouvement diffusent les visiteurs sur le téléphone." }, { name: "Système d’accès professionnel", tag: "Entreprise", description: "RFID, PIN et application pour bureaux, hôtels et bâtiments publics." }], featuresEyebrow: "Conçu dès l’origine", featuresTitle: "Une sécurité qui se fait oublier", features: [{ title: "Accès True-Sensing", description: "La détection longue portée vous reconnaît et déverrouille à votre approche." }, { title: "Multi-biométrie", description: "Paume, empreinte, PIN, carte et application : jusqu’à six modes d’ouverture." }, { title: "Video Guard", description: "Caméra avec détection de mouvement et affichage des visiteurs sur téléphone." }, { title: "Application et scénarios", description: "Ouverture à distance, codes temporaires et scénarios de maison intelligente." }, { title: "Anti-sabotage", description: "Communication chiffrée et structure anti-levier et anti-perçage." }, { title: "Armement automatique", description: "La maison s’arme au départ et se désarme au retour." }], bandEyebrow: "Fabrication intégrée", bandTitle: "Des millions de serrures intelligentes par an sur nos lignes", ctaTitle: "Introduisez les serrures WONLY sur votre marché", ctaSub: "Résidentiel, hôtellerie ou tertiaire : demandez catalogue, échantillons et prix." },
  ru: { seo: { title: "Производитель умных биометрических замков | WONLY", description: "Умные замки WONLY: бесконтактный вход, ладонь и отпечаток, видеонаблюдение, приложение и шифрованная защита для дистрибьюторов и проектов." }, eyebrow: "Умные замки", title: "Бесконтактный вход True-Sensing", sub: "Дальнее распознавание, биометрия и шифрованная защита от вмешательства — умное сердце двери WONLY.", highlights: ["Бесконтактное дальнее распознавание", "Биометрия ладони и отпечатка", "Шифрованная защита от вмешательства"], seriesEyebrow: "Линейка замков", seriesTitle: "Замок для каждой двери", series: [{ name: "Умный замок S80 True-Sensing", tag: "Флагман", description: "Бесконтактное дальнее распознавание, биометрия и управление приложением." }, { name: "Push-pull замок по венам ладони", tag: "Биометрия", description: "Бесконтактное распознавание ладони и ручка push-pull одним движением." }, { name: "Умный замок Video Guard", tag: "С камерой", description: "Встроенная камера и датчик движения передают посетителей на телефон." }, { name: "Коммерческая система доступа", tag: "Бизнес", description: "RFID, PIN и приложение для офисов, гостиниц и общественных зданий." }], featuresEyebrow: "Заложено конструкцией", featuresTitle: "Безопасность, о которой не нужно думать", features: [{ title: "Вход True-Sensing", description: "Дальнее распознавание узнаёт пользователя и открывает замок при приближении." }, { title: "Мультибиометрия", description: "Ладонь, отпечаток, PIN, карта и приложение — до шести способов входа." }, { title: "Video Guard", description: "Камера с датчиком движения показывает посетителей на телефоне." }, { title: "Приложение и сценарии", description: "Удалённое открытие, временные коды и сценарии умного дома." }, { title: "Защита от вмешательства", description: "Шифрованная связь и конструкция против отжима и сверления." }, { title: "Автоматическая охрана", description: "Дом ставится на охрану при уходе и снимается при возвращении." }], bandEyebrow: "Собственное производство", bandTitle: "Миллионы умных замков в год на собственных линиях", ctaTitle: "Выведите умные замки WONLY на свой рынок", ctaSub: "Жильё, гостиницы или бизнес — запросите каталог, образцы и цены." },
  es: { seo: { title: "Fabricante de cerraduras inteligentes biométricas | WONLY", description: "Cerraduras WONLY: acceso manos libres, venas de la palma, huella, vídeo, aplicación y seguridad cifrada antisabotaje para distribuidores y proyectos." }, eyebrow: "Cerraduras inteligentes", title: "Acceso manos libres True-Sensing", sub: "Detección de largo alcance, biometría y seguridad cifrada antisabotaje: el corazón inteligente de la puerta WONLY.", highlights: ["Detección manos libres de largo alcance", "Biometría de palma y huella", "Diseño cifrado antisabotaje"], seriesEyebrow: "Gama de cerraduras", seriesTitle: "Una cerradura para cada puerta", series: [{ name: "Cerradura S80 True-Sensing", tag: "Insignia", description: "Detección de largo alcance manos libres, biometría y control por aplicación." }, { name: "Cerradura push-pull de venas de la palma", tag: "Biométrica", description: "Reconocimiento sin contacto de la palma y manilla push-pull en un movimiento." }, { name: "Cerradura inteligente Video Guard", tag: "Con cámara", description: "Cámara integrada y alertas de movimiento muestran las visitas en el teléfono." }, { name: "Sistema de acceso comercial", tag: "Empresa", description: "RFID, PIN y aplicación para oficinas, hoteles y edificios públicos." }], featuresEyebrow: "Ingeniería integrada", featuresTitle: "Seguridad sin tener que pensar", features: [{ title: "Acceso True-Sensing", description: "La detección de largo alcance reconoce y abre al acercarse." }, { title: "Multibiometría", description: "Palma, huella, PIN, tarjeta y aplicación: hasta seis formas de acceso." }, { title: "Video Guard", description: "Cámara con detección de movimiento transmite las visitas al teléfono." }, { title: "Aplicación y escenas", description: "Apertura remota, contraseñas temporales y escenas de hogar inteligente." }, { title: "Antisabotaje", description: "Comunicación cifrada y estructura antipalanca y antitaladro." }, { title: "Armado automático", description: "La casa se arma al salir y se desarma al regresar." }], bandEyebrow: "Fabricación propia", bandTitle: "Millones de cerraduras inteligentes al año en líneas propias", ctaTitle: "Lleve las cerraduras WONLY a su mercado", ctaSub: "Residencial, hotelero o comercial: solicite catálogo, muestras y precios." },
};

export function localizeSmartLocks(data: ProductPageData, locale: Locale): ProductPageData {
  const c = SMART_LOCK[locale]; if (!c) return data;
  return { ...data, seo: { ...data.seo, ...c.seo }, hero: { ...data.hero, eyebrow: c.eyebrow, title: c.title, sub: c.sub }, highlights: c.highlights, seriesEyebrow: c.seriesEyebrow, seriesTitle: c.seriesTitle, series: data.series.map((item, i) => ({ ...item, name: c.series[i]?.name ?? item.name, tag: c.series[i]?.tag ?? item.tag, d: c.series[i]?.description ?? item.d })), featuresEyebrow: c.featuresEyebrow, featuresTitle: c.featuresTitle, features: data.features.map((item, i) => ({ ...item, t: c.features[i]?.title ?? item.t, d: c.features[i]?.description ?? item.d })), band: { ...data.band, eyebrow: c.bandEyebrow, title: c.bandTitle }, cta: { title: c.ctaTitle, sub: c.ctaSub } };
}

const SMART_WINDOW: Partial<Record<Locale, WoodenCopy>> = {
  ar: { seo: { title: "مورّد نوافذ ألمنيوم ذكية موفرة للطاقة | WONLY", description: "نوافذ WONLY الذكية: عزل حراري وصوتي، إغلاق تلقائي مع الرياح والمطر، أكثر من 50,000 دورة، تحكم بالتطبيق وسلسلة مقاومة للأعاصير." }, eyebrow: "نوافذ ألمنيوم ذكية", title: "الدفء في الداخل والطقس في الخارج", sub: "عزل حراري وصوتي يضاهي الجدار، ونوافذ تغلق تلقائياً عند وصول العاصفة.", highlights: ["إغلاق تلقائي مع الرياح والمطر", "أكثر من 50,000 دورة انزلاق دون تشوه", "تحكم عن بعد ومشاهد عبر التطبيق"], seriesEyebrow: "مجموعة النوافذ", seriesTitle: "نظام لكل فتحة", series: [{ name: "نافذة مفصلية موفرة للطاقة", tag: "الأكثر مبيعاً", description: "ألمنيوم بفاصل حراري يعزل كالجدار، هادئ ومحكم وفعال." }, { name: "نافذة ذكية بإغلاق تلقائي", tag: "ذكية", description: "تستشعر الرياح والمطر وتغلق، وتفتح للتهوية عند الدخان أو تسرب الغاز." }, { name: "سلسلة الأعاصير", tag: "مدعمة", description: "أنظمة مقاومة للعواصف لأسواق أمريكا الشمالية والكاريبي." }], featuresEyebrow: "ذكاء في التصميم", featuresTitle: "نافذة تعتني بنفسها", features: [{ title: "إغلاق تلقائي في الطقس السيئ", description: "تستشعر تغير الطقس وتغلق تلقائياً لحماية المنزل." }, { title: "تهوية الدخان والغاز", description: "تفتح للتهوية الآمنة عند اكتشاف دخان أو تسرب غاز." }, { title: "عزل بمستوى الجدار", description: "هيكل بفاصل حراري يوفر عزلاً حرارياً وصوتياً عالياً." }, { title: "ربط عن بعد بالتطبيق", description: "فتح وإغلاق وجدولة من أي مكان بلمسة واحدة." }, { title: "اختبار أكثر من 50,000 دورة", description: "اختبارات انزلاق تتجاوز 50,000 مرة دون تشوه." }, { title: "سلسلة الأعاصير", description: "أنظمة مدعمة لأسواق أمريكا الشمالية والكاريبي." }], bandEyebrow: "غلاف المبنى", bandTitle: "نوافذ تكمل منظومة المنزل بالكامل", ctaTitle: "أدخل نوافذ WONLY الذكية إلى سوقك", ctaSub: "موفرة للطاقة أو للشرفات أو مقاومة للأعاصير، اطلب المواصفات والأسعار." },
  fr: { seo: { title: "Fournisseur de fenêtres aluminium intelligentes et économes | WONLY", description: "Fenêtres WONLY : isolation thermique et acoustique, fermeture automatique vent/pluie, plus de 50 000 cycles, application et série anti-ouragan." }, eyebrow: "Fenêtres aluminium intelligentes", title: "La chaleur dedans, les intempéries dehors", sub: "Une isolation thermique et acoustique comparable à un mur, avec fermeture automatique dès l’arrivée d’une tempête.", highlights: ["Fermeture automatique par vent et pluie", "Plus de 50 000 cycles sans déformation", "Commande à distance et scénarios par application"], seriesEyebrow: "Gamme de fenêtres", seriesTitle: "Un système pour chaque ouverture", series: [{ name: "Fenêtre à battant écoénergétique", tag: "Meilleure vente", description: "Aluminium à rupture thermique, silencieux, étanche et efficace comme un mur." }, { name: "Fenêtre intelligente à fermeture automatique", tag: "Intelligente", description: "Détecte vent et pluie, se ferme, puis s’ouvre pour ventiler en cas de fumée ou de gaz." }, { name: "Série anti-ouragan", tag: "Renforcée", description: "Systèmes résistants aux tempêtes pour l’Amérique du Nord et les Caraïbes." }], featuresEyebrow: "Intelligente par conception", featuresTitle: "La fenêtre qui veille sur elle-même", features: [{ title: "Fermeture automatique par mauvais temps", description: "Détecte les changements météo et se ferme pour protéger le logement." }, { title: "Ventilation fumée et gaz", description: "S’ouvre pour ventiler en sécurité lorsqu’elle détecte fumée ou fuite de gaz." }, { title: "Isolation comparable à un mur", description: "La rupture thermique assure une forte isolation thermique et acoustique." }, { title: "Commande à distance", description: "Ouverture, fermeture et programmation depuis n’importe où." }, { title: "Testée sur plus de 50 000 cycles", description: "Plus de 50 000 coulissements sans déformation." }, { title: "Série anti-ouragan", description: "Systèmes renforcés pour l’Amérique du Nord et les Caraïbes." }], bandEyebrow: "Enveloppe du bâtiment", bandTitle: "Des fenêtres qui complètent le système de la maison", ctaTitle: "Introduisez les fenêtres WONLY sur votre marché", ctaSub: "Économie d’énergie, balcon/terrasse ou anti-ouragan : demandez spécifications et prix." },
  ru: { seo: { title: "Поставщик умных энергосберегающих алюминиевых окон | WONLY", description: "Окна WONLY: тепло- и шумоизоляция, автозакрытие при ветре и дожде, более 50 000 циклов, приложение и ураганостойкая серия." }, eyebrow: "Алюминиевые и умные окна", title: "Тепло внутри, непогода снаружи", sub: "Тепло- и шумоизоляция уровня стены, автоматическое закрытие при приближении непогоды.", highlights: ["Автозакрытие при ветре и дожде", "Более 50 000 циклов без деформации", "Удалённое управление и сценарии"], seriesEyebrow: "Линейка окон", seriesTitle: "Система для каждого проёма", series: [{ name: "Энергосберегающее распашное окно", tag: "Хит продаж", description: "Алюминий с терморазрывом: тишина, герметичность и эффективная изоляция." }, { name: "Умное окно с автозакрытием", tag: "Умное", description: "Реагирует на ветер и дождь, а при дыме или газе открывается для вентиляции." }, { name: "Ураганостойкая серия", tag: "Усиленная", description: "Штормостойкие системы для Северной Америки и Карибского региона." }], featuresEyebrow: "Интеллект в конструкции", featuresTitle: "Окно, которое заботится о себе", features: [{ title: "Автозакрытие в непогоду", description: "Распознаёт изменение погоды и автоматически защищает дом." }, { title: "Вентиляция при дыме и газе", description: "Открывается для безопасного проветривания при обнаружении дыма или утечки." }, { title: "Изоляция уровня стены", description: "Терморазрыв обеспечивает высокую тепло- и шумоизоляцию." }, { title: "Удалённое управление", description: "Открытие, закрытие и расписание из любой точки." }, { title: "Испытано на 50 000+ циклов", description: "Более 50 000 циклов скольжения без деформации." }, { title: "Ураганостойкая серия", description: "Усиленные системы для Северной Америки и Карибского региона." }], bandEyebrow: "Оболочка здания", bandTitle: "Окна, завершающие систему всего дома", ctaTitle: "Выведите умные окна WONLY на свой рынок", ctaSub: "Энергосберегающие, балконные или ураганостойкие серии — запросите характеристики и цены." },
  es: { seo: { title: "Proveedor de ventanas inteligentes de aluminio y ahorro energético | WONLY", description: "Ventanas WONLY: aislamiento térmico y acústico, cierre automático con viento y lluvia, más de 50.000 ciclos, aplicación y serie antihuracán." }, eyebrow: "Ventanas inteligentes de aluminio", title: "El calor dentro, el clima fuera", sub: "Aislamiento térmico y acústico comparable a un muro y cierre automático cuando llega la tormenta.", highlights: ["Cierre automático con viento y lluvia", "Más de 50.000 ciclos sin deformación", "Control remoto y escenas por aplicación"], seriesEyebrow: "Gama de ventanas", seriesTitle: "Un sistema para cada abertura", series: [{ name: "Ventana abatible de ahorro energético", tag: "Más vendida", description: "Aluminio con rotura térmica, silencioso, hermético y eficiente como un muro." }, { name: "Ventana inteligente de cierre automático", tag: "Inteligente", description: "Detecta viento y lluvia, se cierra y abre para ventilar ante humo o gas." }, { name: "Serie antihuracán", tag: "Reforzada", description: "Sistemas resistentes a tormentas para Norteamérica y el Caribe." }], featuresEyebrow: "Inteligente por diseño", featuresTitle: "La ventana que se cuida sola", features: [{ title: "Cierre automático con mal tiempo", description: "Detecta cambios meteorológicos y se cierra para proteger el hogar." }, { title: "Ventilación de humo y gas", description: "Se abre para ventilar con seguridad al detectar humo o fuga de gas." }, { title: "Aislamiento como un muro", description: "La rotura térmica ofrece alto aislamiento térmico y acústico." }, { title: "Control remoto por aplicación", description: "Abra, cierre y programe desde cualquier lugar." }, { title: "Probada en más de 50.000 ciclos", description: "Más de 50.000 deslizamientos sin deformación." }, { title: "Serie antihuracán", description: "Sistemas reforzados para Norteamérica y el Caribe." }], bandEyebrow: "Envolvente del edificio", bandTitle: "Ventanas que completan el sistema de toda la vivienda", ctaTitle: "Lleve las ventanas WONLY a su mercado", ctaSub: "Ahorro energético, balcón/terraza o antihuracán: solicite especificaciones y precios." },
};

export function localizeSmartWindows(data: ProductPageData, locale: Locale): ProductPageData {
  const c = SMART_WINDOW[locale]; if (!c) return data;
  return { ...data, seo: { ...data.seo, ...c.seo }, hero: { ...data.hero, eyebrow: c.eyebrow, title: c.title, sub: c.sub }, highlights: c.highlights, seriesEyebrow: c.seriesEyebrow, seriesTitle: c.seriesTitle, series: data.series.map((item, i) => ({ ...item, name: c.series[i]?.name ?? item.name, tag: c.series[i]?.tag ?? item.tag, d: c.series[i]?.description ?? item.d })), featuresEyebrow: c.featuresEyebrow, featuresTitle: c.featuresTitle, features: data.features.map((item, i) => ({ ...item, t: c.features[i]?.title ?? item.t, d: c.features[i]?.description ?? item.d })), band: { ...data.band, eyebrow: c.bandEyebrow, title: c.bandTitle }, cta: { title: c.ctaTitle, sub: c.ctaSub } };
}

type WholeCopy = WoodenCopy & { ecosystemEyebrow: string; ecosystemTitle: string; ecosystemItems: string[] };
const WHOLE_HOUSE: Partial<Record<Locale, WholeCopy>> = {
  ar: { seo: { title: "نظام منزل ذكي متكامل للأبواب والأقفال والحساسات | WONLY", description: "منظومة WONLY للمنزل الذكي تبدأ من الباب الأمامي وتجمع 28 فئة من المنتجات ونظامين ومحوراً مركزياً لمشاهد الأمان والحياة الذكية." }, eyebrow: "ذكاء المنزل بالكامل · WONLY Smart Home", title: "مدخل واحد، منزل أكثر ذكاءً", sub: "يبدأ من الباب الأمامي الذكي: 28 فئة من المنتجات ونظامان ومحور مركزي يدير المنزل بالكامل.", highlights: ["باب الدخول هو بوابة المنزل الذكي", "28 فئة من المنتجات الذكية", "نظامان + محور واحد + مشاهد ذكية متعددة"], seriesEyebrow: "المنظومة", seriesTitle: "نظامان ومنزل واحد متصل", series: [{ name: "محور التحكم المركزي", tag: "المركز", description: "يربط جميع الأجهزة في واجهة واحدة ويدير المشاهد بالذكاء الاصطناعي." }, { name: "الدخول والأقفال الذكية", tag: "المدخل", description: "الباب الأمامي الذكي هو بوابة المنزل المتصل بالكامل." }, { name: "المشاهد والأتمتة", tag: "المعيشة", description: "مشاهد المغادرة والنوم والترحيب بالصوت أو بلمسة." }], featuresEyebrow: "منظومة واحدة متصلة", featuresTitle: "أمان وراحة بتناغم", features: [{ title: "المدخل كبوابة", description: "الباب الذكي هو نقطة الدخول إلى منظومة المنزل المتصل." }, { title: "28 فئة من المنتجات", description: "أقفال وحساسات وإضاءة ومناخ ومراقبة ضمن عائلة واحدة." }, { title: "محور تحكم مركزي", description: "نظامان ومحور واحد يربطان جميع الأجهزة في تجربة موحدة." }, { title: "مشاهد ذكية", description: "أتمتة المغادرة والنوم والعودة بكلمة أو لمسة." }, { title: "أمان بالذكاء الاصطناعي", description: "يتسلح المنزل عند المغادرة ويلغي الحماية عند العودة." }, { title: "مساعد نوم ذكي", description: "يضبط البيئة بهدوء لراحة أعمق وأفضل." }], bandEyebrow: "حياة متصلة", bandTitle: "من الباب الأمامي إلى كل غرفة", ecosystemEyebrow: "منظومة المنزل الذكي", ecosystemTitle: "28 فئة، منزل واحد متصل", ecosystemItems: ["حساس وجود", "حساس جودة الهواء", "كشف السقوط", "حساس إضاءة", "موقد مدمج", "أريكة ذكية"], ctaTitle: "أدخل حياة WONLY الذكية إلى سوقك", ctaSub: "اسأل عن المنظومة والتكامل وخيارات OEM/ODM؛ نرد خلال 24 ساعة." },
  fr: { seo: { title: "Système maison intelligente complet : portes, serrures et capteurs | WONLY", description: "La maison intelligente WONLY part de la porte d’entrée et réunit 28 catégories, deux systèmes et un hub pour orchestrer sécurité IA et scènes de vie." }, eyebrow: "Intelligence de toute la maison · WONLY Smart Home", title: "Une entrée, une maison plus intelligente", sub: "Tout commence à la porte intelligente : 28 catégories, deux systèmes et un hub central pour orchestrer la maison.", highlights: ["La porte d’entrée, passerelle de la maison intelligente", "28 catégories de produits intelligents", "2 systèmes + 1 hub + N scénarios"], seriesEyebrow: "L’écosystème", seriesTitle: "Deux systèmes, une maison connectée", series: [{ name: "Hub de contrôle central", tag: "Cœur", description: "Un hub réunit tous les appareils dans une interface et orchestre les scénarios par IA." }, { name: "Entrée et serrures intelligentes", tag: "Entrée", description: "La porte intelligente devient la passerelle de toute la maison connectée." }, { name: "Scénarios et automatisation", tag: "Vie", description: "Départ, sommeil et accueil automatisés par la voix ou un geste." }], featuresEyebrow: "Un écosystème connecté", featuresTitle: "Sécurité et confort orchestrés", features: [{ title: "L’entrée comme passerelle", description: "La porte intelligente est le point d’accès à toute la maison connectée." }, { title: "28 catégories de produits", description: "Serrures, capteurs, éclairage, climat et surveillance dans une même famille." }, { title: "Hub de contrôle central", description: "Deux systèmes et un hub réunissent tous les appareils." }, { title: "Scénarios intelligents", description: "Départ, sommeil et retour automatisés par une parole ou un geste." }, { title: "Sécurité IA", description: "La maison s’arme au départ et se désarme au retour." }, { title: "Assistant sommeil IA", description: "L’environnement s’ajuste discrètement pour un repos plus profond." }], bandEyebrow: "Vie connectée", bandTitle: "De la porte d’entrée à chaque pièce", ecosystemEyebrow: "Écosystème maison intelligente", ecosystemTitle: "28 catégories, une maison connectée", ecosystemItems: ["Capteur de présence", "Capteur de qualité de l’air", "Détection de chute", "Capteur de lumière", "Plaque de cuisson intégrée", "Canapé intelligent"], ctaTitle: "Introduisez l’habitat intelligent WONLY sur votre marché", ctaSub: "Découvrez l’écosystème, l’intégration et les options OEM/ODM ; réponse sous 24 heures." },
  ru: { seo: { title: "Система умного дома: двери, замки и датчики | WONLY", description: "Умный дом WONLY начинается с входной двери и объединяет 28 категорий, две системы и центральный хаб для ИИ-безопасности и сценариев." }, eyebrow: "Интеллект всего дома · WONLY Smart Home", title: "Один вход — более умный дом", sub: "Всё начинается с умной входной двери: 28 категорий, две системы и центральный хаб управляют всем домом.", highlights: ["Входная дверь — шлюз умного дома", "28 категорий умных продуктов", "2 системы + 1 хаб + множество сценариев"], seriesEyebrow: "Экосистема", seriesTitle: "Две системы, один связанный дом", series: [{ name: "Центральный хаб", tag: "Ядро", description: "Объединяет устройства в одном интерфейсе и управляет ИИ-сценариями." }, { name: "Умный вход и замки", tag: "Вход", description: "Интеллектуальная входная дверь служит шлюзом всего связанного дома." }, { name: "Сценарии и автоматизация", tag: "Жизнь", description: "Режимы ухода, сна и возвращения по слову или касанию." }], featuresEyebrow: "Единая экосистема", featuresTitle: "Согласованные безопасность и комфорт", features: [{ title: "Вход как шлюз", description: "Умная дверь — точка входа во всю систему связанного дома." }, { title: "28 категорий продуктов", description: "Замки, датчики, свет, климат и мониторинг в одной семье." }, { title: "Центральный хаб", description: "Две системы и один хаб объединяют все устройства." }, { title: "Умные сценарии", description: "Автоматизация ухода, сна и возвращения голосом или касанием." }, { title: "ИИ-безопасность", description: "Дом ставится на охрану при уходе и снимается при возвращении." }, { title: "ИИ-помощник сна", description: "Среда незаметно настраивается для более глубокого отдыха." }], bandEyebrow: "Связанная жизнь", bandTitle: "От входной двери до каждой комнаты", ecosystemEyebrow: "Экосистема умного дома", ecosystemTitle: "28 категорий, один связанный дом", ecosystemItems: ["Датчик присутствия", "Датчик качества воздуха", "Обнаружение падения", "Датчик света", "Встроенная плита", "Умный диван"], ctaTitle: "Выведите умный дом WONLY на свой рынок", ctaSub: "Узнайте об экосистеме, интеграции и OEM/ODM; ответим в течение 24 часов." },
  es: { seo: { title: "Sistema integral de hogar inteligente: puertas, cerraduras y sensores | WONLY", description: "El hogar inteligente WONLY parte de la puerta de entrada y reúne 28 categorías, dos sistemas y un hub para seguridad con IA y escenas automatizadas." }, eyebrow: "Inteligencia para toda la casa · WONLY Smart Home", title: "Una entrada, un hogar más inteligente", sub: "Comienza en la puerta inteligente: 28 categorías, dos sistemas y un hub central coordinan toda la vivienda.", highlights: ["La puerta de entrada es la pasarela del hogar inteligente", "28 categorías de productos inteligentes", "2 sistemas + 1 hub + múltiples escenas"], seriesEyebrow: "El ecosistema", seriesTitle: "Dos sistemas, un hogar conectado", series: [{ name: "Hub de control central", tag: "Núcleo", description: "Reúne todos los dispositivos en una interfaz y coordina escenas con IA." }, { name: "Entrada y cerraduras inteligentes", tag: "Entrada", description: "La puerta inteligente es la pasarela de todo el hogar conectado." }, { name: "Escenas y automatización", tag: "Vida", description: "Modos de salida, sueño y bienvenida con voz o un toque." }], featuresEyebrow: "Un ecosistema conectado", featuresTitle: "Seguridad y confort coordinados", features: [{ title: "La entrada como pasarela", description: "La puerta inteligente es el punto de acceso a todo el hogar conectado." }, { title: "28 categorías de productos", description: "Cerraduras, sensores, iluminación, clima y vigilancia en una familia." }, { title: "Hub de control central", description: "Dos sistemas y un hub conectan todos los dispositivos." }, { title: "Escenas inteligentes", description: "Automatización de salida, sueño y regreso por voz o toque." }, { title: "Seguridad con IA", description: "La casa se arma al salir y se desarma al regresar." }, { title: "Asistente de sueño con IA", description: "El entorno se ajusta discretamente para un descanso más profundo." }], bandEyebrow: "Vida conectada", bandTitle: "Desde la puerta de entrada hasta cada habitación", ecosystemEyebrow: "Ecosistema de hogar inteligente", ecosystemTitle: "28 categorías, un hogar conectado", ecosystemItems: ["Sensor de presencia", "Sensor de calidad del aire", "Detección de caídas", "Sensor de luz", "Cocina integrada", "Sofá inteligente"], ctaTitle: "Lleve la vida inteligente WONLY a su mercado", ctaSub: "Consulte ecosistema, integración y opciones OEM/ODM; respondemos en 24 horas." },
};

export function localizeWholeHouse(data: ProductPageData, locale: Locale): ProductPageData {
  const c = WHOLE_HOUSE[locale]; if (!c) return data;
  return { ...data, seo: { ...data.seo, ...c.seo }, hero: { ...data.hero, eyebrow: c.eyebrow, title: c.title, sub: c.sub }, highlights: c.highlights, seriesEyebrow: c.seriesEyebrow, seriesTitle: c.seriesTitle, series: data.series.map((item, i) => ({ ...item, name: c.series[i]?.name ?? item.name, tag: c.series[i]?.tag ?? item.tag, d: c.series[i]?.description ?? item.d })), featuresEyebrow: c.featuresEyebrow, featuresTitle: c.featuresTitle, features: data.features.map((item, i) => ({ ...item, t: c.features[i]?.title ?? item.t, d: c.features[i]?.description ?? item.d })), band: { ...data.band, eyebrow: c.bandEyebrow, title: c.bandTitle }, ecosystem: data.ecosystem ? { ...data.ecosystem, eyebrow: c.ecosystemEyebrow, title: c.ecosystemTitle, items: data.ecosystem.items.map((item, i) => ({ ...item, name: c.ecosystemItems[i] ?? item.name })) } : undefined, cta: { title: c.ctaTitle, sub: c.ctaSub } };
}
