import { ArrowRight, Check } from "lucide-react";
import { Link } from "react-router-dom";
import { useSeo, SITE_URL } from "@/lib/seo";
import { BASE, CHAMP, CHAMP_BG, DARK, GOLD, GOLD_DEEP, MUTED, SiteFooter, SiteHeader, eyebrow, h2cls, useQuoteStore } from "@/lib/site-ui";
import { DoorModelSelector } from "@/lib/DoorModelSelector";

type SeriesKey = "custom" | "minimalist" | "pvc" | "solid-wood" | "aluminum-alloy";
const SERIES: Record<SeriesKey, { name: string; path: string; image: string; description: string; models: string[]; focus: string[] }> = {
  custom: { name: "Custom Wooden Door Series", path: "/products/wooden-doors/custom", image: `${BASE}images/catalog-2026/hero-renders/wood-custom.webp`, description: "Bespoke interior wooden doors developed around the room concept, finish direction and project specification.", models: ["WL-G027", "WL-G022", "WL-G025", "WL-G026"], focus: ["Project-led design selection", "Coordinated colours and finishes", "Residential and hospitality interiors"] },
  minimalist: { name: "Minimalist Wooden Door Series", path: "/products/wooden-doors/minimalist", image: `${BASE}images/catalog-2026/hero-renders/wood-minimalist.webp`, description: "Clean-lined soundproof wooden doors for contemporary apartments, villas and modern commercial interiors.", models: ["WL-D and WL-J model families", "Multiple catalogue finishes", "Single and paired interior applications"], focus: ["Minimal visual language", "Broad model and finish selection", "Sound-conscious interior planning"] },
  pvc: { name: "PVC Wooden Door Series", path: "/products/wooden-doors/pvc", image: `${BASE}images/catalog-2026/hero-renders/wood-pvc.webp`, description: "Practical PVC-finished wooden doors designed for repeatable interior programmes and consistent surface appearance.", models: ["WL-P002", "WL-P012", "WL-P102B"], focus: ["Easy-care surface options", "Repeatable project specification", "Multiple catalogue colours"] },
  "solid-wood": { name: "Solid Wood Door Series", path: "/products/wooden-doors/solid-wood", image: `${BASE}images/catalog-2026/hero-renders/wood-solid.webp`, description: "A premium solid-wood collection combining natural visual depth with WONLY interior-door craftsmanship.", models: ["WL-S model family", "WL-BS model family", "Catalogue colour-board options"], focus: ["Natural premium character", "Classic and contemporary designs", "Whole-home coordination"] },
  "aluminum-alloy": { name: "Aluminum Alloy Interior Door Series", path: "/products/wooden-doors/aluminum-alloy", image: `${BASE}images/catalog-2026/hero-renders/wood-aluminum.webp`, description: "Slim aluminum-alloy framed doors for spaces that need light transmission, visual separation and coordinated hardware.", models: ["Multiple frame profiles", "Glass configuration options", "Catalogue colours and crafts"], focus: ["Slim modern profiles", "Glass and finish choice", "Kitchens, studies and living spaces"] },
};

export default function WoodenDoorSeriesDetail({ series }: { series: SeriesKey }) {
  const data = SERIES[series];
  const openQuote = useQuoteStore((s) => s.openQuote);
  const description = `${data.name} by WONLY: explore catalogue models, finishes and project options, then request specifications and a tailored quotation.`;
  useSeo({ title: `${data.name} Manufacturer | WONLY`, description, path: data.path, image: `${SITE_URL}${data.image.replace(BASE, "/")}`, type: "product", localized: false, jsonLd: { "@context": "https://schema.org", "@type": "CollectionPage", name: data.name, description, url: `${SITE_URL}${data.path}/` } });
  return <div className="font-sans" style={{ background: CHAMP_BG, color: DARK }}><SiteHeader /><main>
    <section className="relative min-h-[72vh] flex items-end overflow-hidden"><img src={data.image} alt={data.name} className="absolute inset-0 w-full h-full object-cover" fetchPriority="high" /><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/55 to-black/5" /><div className="relative z-10 px-[7vw] pb-16 md:pb-24 w-full md:max-w-[54%] text-white"><nav className="text-xs text-white/70 mb-7"><Link to="/">Home</Link> / <Link to="/products/wooden-doors">Wooden Doors</Link> / {data.name}</nav><div className={eyebrow} style={{ color: CHAMP }}>Soundproof Wooden Doors</div><h1 className="mt-5 text-[40px] md:text-[58px] font-light leading-tight">{data.name}</h1><p className="mt-5 max-w-2xl text-lg text-white/80 leading-8">{data.description}</p><button onClick={() => openQuote({ subject: data.name })} className="mt-8 inline-flex gap-2 items-center rounded-full px-7 py-4 text-sm font-semibold" style={{ background: GOLD, color: DARK }}>Get Specifications &amp; Quote <ArrowRight size={16} /></button></div></section>
    <section className="px-[7vw] py-20 md:py-28 bg-white"><div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-14"><div><div className={eyebrow} style={{ color: GOLD_DEEP }}>Series Overview</div><h2 className={h2cls + " mt-4"}>Models and Options</h2><div className="mt-8 space-y-4">{data.models.map((item) => <div className="flex gap-3" key={item}><Check size={18} style={{ color: GOLD }} /><span>{item}</span></div>)}</div></div><div><div className={eyebrow} style={{ color: GOLD_DEEP }}>Best Suited To</div><div className="mt-8 space-y-4">{data.focus.map((item) => <div className="rounded-xl p-5 flex gap-3" style={{ background: CHAMP_BG }} key={item}><Check size={18} style={{ color: GOLD }} /><span>{item}</span></div>)}</div></div></div></section>
    <DoorModelSelector group="wooden" currentPath={data.path} />
    <section className="px-[7vw] py-24 text-center"><div className="max-w-3xl mx-auto"><h2 className={h2cls}>Specify the Right Door for Your Project</h2><p className="mt-5" style={{ color: MUTED }}>Share the required design direction, dimensions, quantity and application. WONLY sales will confirm the appropriate model, finish and project configuration.</p><button onClick={() => openQuote({ subject: data.name })} className="mt-8 inline-flex gap-2 items-center rounded-full px-8 py-4 text-sm font-semibold" style={{ background: GOLD, color: DARK }}>Contact WONLY Sales <ArrowRight size={16} /></button></div></section>
  </main><SiteFooter /></div>;
}
