create table if not exists public.cms_quality_runs(
 id uuid primary key default gen_random_uuid(),page_id uuid not null references public.cms_pages(id) on delete cascade,route text not null,requested_version bigint not null,status text not null default 'queued' check(status in('queued','running','completed','failed')),scores jsonb,summary jsonb,requested_by uuid not null references auth.users(id),requested_at timestamptz not null default now(),started_at timestamptz,finished_at timestamptz,error_message text not null default ''
);
create table if not exists public.cms_quality_issues(
 id uuid primary key default gen_random_uuid(),run_id uuid not null references public.cms_quality_runs(id) on delete cascade,category text not null check(category in('seo','accessibility','links','images','performance','mobile')),severity text not null check(severity in('error','warning','info')),rule_key text not null,message text not null,selector text,evidence jsonb not null default '{}'::jsonb
);
alter table public.cms_quality_runs enable row level security;alter table public.cms_quality_issues enable row level security;grant select on public.cms_quality_runs,public.cms_quality_issues to authenticated;revoke insert,update,delete on public.cms_quality_runs,public.cms_quality_issues from authenticated;
create policy "CMS reads quality runs" on public.cms_quality_runs for select to authenticated using(public.cms_can('read'));create policy "CMS reads quality issues" on public.cms_quality_issues for select to authenticated using(public.cms_can('read'));
create index if not exists cms_quality_runs_page_time_idx on public.cms_quality_runs(page_id,requested_at desc);create index if not exists cms_quality_issues_run_idx on public.cms_quality_issues(run_id,severity,category);

create or replace function public.cms_request_quality_run(p_page_id uuid) returns public.cms_quality_runs language plpgsql security definer set search_path=public as $$ declare v_page public.cms_pages;v_run public.cms_quality_runs;
begin if not public.cms_can('read') then raise exception 'permission_denied';end if;select * into v_page from public.cms_pages where id=p_page_id;if v_page.id is null then raise exception 'page_not_found';end if;
 insert into public.cms_quality_runs(page_id,route,requested_version,requested_by) values(v_page.id,v_page.route,v_page.content_version,auth.uid()) returning * into v_run;insert into public.cms_audit_logs(actor_id,action,resource_type,resource_id,metadata) values(auth.uid(),'quality_scan_requested','quality_run',v_run.id::text,jsonb_build_object('page_id',p_page_id,'version',v_page.content_version));return v_run;end $$;

create or replace function public.cms_record_quality_run(p_run_id uuid,p_status text,p_scores jsonb default null,p_summary jsonb default null,p_issues jsonb default '[]',p_error_message text default '') returns public.cms_quality_runs language plpgsql security definer set search_path=public as $$ declare v_run public.cms_quality_runs;issue jsonb;v_role text:=coalesce(current_setting('request.jwt.claim.role',true),'');begin
 if v_role<>'service_role' then raise exception 'service_role_required';end if;if p_status not in('running','completed','failed') then raise exception 'invalid_quality_status';end if;
 update public.cms_quality_runs set status=p_status,scores=p_scores,summary=p_summary,error_message=left(coalesce(p_error_message,''),1000),started_at=case when p_status='running' then coalesce(started_at,now()) else started_at end,finished_at=case when p_status in('completed','failed') then now() else finished_at end where id=p_run_id and status not in('completed','failed') returning * into v_run;if v_run.id is null then raise exception 'quality_run_not_mutable';end if;
 if p_status='completed' then delete from public.cms_quality_issues where run_id=p_run_id;for issue in select value from jsonb_array_elements(coalesce(p_issues,'[]')) loop insert into public.cms_quality_issues(run_id,category,severity,rule_key,message,selector,evidence) values(p_run_id,issue->>'category',issue->>'severity',issue->>'rule_key',left(issue->>'message',1000),issue->>'selector',coalesce(issue->'evidence','{}'));end loop;end if;return v_run;end $$;

revoke execute on function public.cms_request_quality_run(uuid),public.cms_record_quality_run(uuid,text,jsonb,jsonb,jsonb,text) from public,anon;grant execute on function public.cms_request_quality_run(uuid) to authenticated;grant execute on function public.cms_record_quality_run(uuid,text,jsonb,jsonb,jsonb,text) to service_role;
