-- Server-observed integration health; never stores credentials.
create table if not exists public.cms_integrations(id uuid primary key default gen_random_uuid(),integration_key text not null unique,name text not null,category text not null,configured boolean not null default false,enabled boolean not null default true,secret_refs text[] not null default '{}',last_status text not null default 'not_configured' check(last_status in('not_configured','unknown','healthy','degraded','failed')),last_checked_at timestamptz,last_latency_ms integer,last_error text,updated_at timestamptz not null default now());
create table if not exists public.cms_integration_checks(id uuid primary key default gen_random_uuid(),integration_id uuid not null references public.cms_integrations(id) on delete cascade,status text not null default 'pending' check(status in('pending','running','healthy','degraded','failed','not_configured')),requested_by uuid not null references auth.users(id),requested_at timestamptz not null default now(),completed_at timestamptz,http_status integer,latency_ms integer,error_message text,evidence jsonb not null default '{}');
insert into public.cms_integrations(integration_key,name,category,secret_refs) values('deepseek','DeepSeek AI','content',array['DEEPSEEK_API_KEY']),('ga4','Google Analytics 4','analytics',array['GOOGLE_SA_KEY','GA4_PROPERTY_ID']),('gsc','Google Search Console','analytics',array['GOOGLE_SA_KEY','GSC_SITE']),('supabase','Supabase CMS','data',array['CMS_SUPABASE_URL','CMS_SUPABASE_SERVICE_ROLE_KEY']),('crm','CRM inquiry sync','sales',array['CRM_HEALTH_URL']),('web3forms','Website email form','forms',array['WEB3FORMS_ACCESS_KEY']),('deployment','Deployment service','delivery',array['CMS_DEPLOY_API_URL']) on conflict(integration_key) do nothing;
alter table public.cms_integrations enable row level security;alter table public.cms_integration_checks enable row level security;grant select on public.cms_integrations,public.cms_integration_checks to authenticated;
create policy "CMS reads integrations" on public.cms_integrations for select to authenticated using(public.cms_can('read'));create policy "CMS reads integration checks" on public.cms_integration_checks for select to authenticated using(public.cms_can('read'));
create or replace function public.cms_request_integration_check(p_integration_id uuid) returns public.cms_integration_checks language plpgsql security definer set search_path=public as $$ declare v public.cms_integration_checks;begin if public.cms_current_role()<>'super_admin' then raise exception 'permission_denied';end if;if exists(select 1 from public.cms_integration_checks where integration_id=p_integration_id and status in('pending','running') and requested_at>now()-interval '5 minutes')then raise exception 'check_already_running';end if;insert into public.cms_integration_checks(integration_id,requested_by)values(p_integration_id,auth.uid())returning * into v;return v;end $$;
create or replace function public.cms_record_integration_check(p_check_id uuid,p_status text,p_http_status integer,p_latency_ms integer,p_error text,p_evidence jsonb) returns void language plpgsql security definer set search_path=public as $$ declare v_integration uuid;begin if auth.role()<>'service_role' then raise exception 'service_role_required';end if;if p_status not in('healthy','degraded','failed','not_configured') then raise exception 'invalid_health_status';end if;update public.cms_integration_checks set status=p_status,http_status=p_http_status,latency_ms=p_latency_ms,error_message=left(p_error,500),evidence=coalesce(p_evidence,'{}'),completed_at=now() where id=p_check_id and status in('pending','running') returning integration_id into v_integration;if not found then raise exception 'check_not_mutable';end if;update public.cms_integrations set configured=p_status<>'not_configured',last_status=p_status,last_checked_at=now(),last_latency_ms=p_latency_ms,last_error=left(p_error,500),updated_at=now() where id=v_integration;end $$;
revoke execute on function public.cms_request_integration_check(uuid),public.cms_record_integration_check(uuid,text,integer,integer,text,jsonb) from public,anon;grant execute on function public.cms_request_integration_check(uuid) to authenticated;grant execute on function public.cms_record_integration_check(uuid,text,integer,integer,text,jsonb) to service_role;
