create table if not exists public.cms_environments(
 id uuid primary key default gen_random_uuid(),environment_key text not null unique check(environment_key in('development','staging','production')),name text not null,base_url text not null,health_url text not null,provider text not null,branch text not null,is_protected boolean not null default false,last_health_status text not null default 'unknown' check(last_health_status in('unknown','healthy','degraded','down')),last_health_checked_at timestamptz,last_deployed_revision text,last_deployed_at timestamptz,updated_at timestamptz not null default now()
);
create table if not exists public.cms_releases(
 id uuid primary key default gen_random_uuid(),environment_id uuid not null references public.cms_environments(id),revision text not null,summary text not null,artifact_digest text,status text not null default 'requested' check(status in('requested','approved','queued','deploying','succeeded','failed','cancelled')),requested_by uuid not null references auth.users(id),approved_by uuid references auth.users(id),requested_at timestamptz not null default now(),approved_at timestamptz,started_at timestamptz,finished_at timestamptz,provider_run_url text,error_message text not null default ''
);
alter table public.cms_environments enable row level security;alter table public.cms_releases enable row level security;
grant select on public.cms_environments,public.cms_releases to authenticated;revoke insert,update,delete on public.cms_environments,public.cms_releases from authenticated;
create policy "CMS reads environments" on public.cms_environments for select to authenticated using(public.cms_can('read'));
create policy "CMS reads releases" on public.cms_releases for select to authenticated using(public.cms_can('read'));
create index if not exists cms_releases_environment_time_idx on public.cms_releases(environment_id,requested_at desc);

create or replace function public.cms_request_release(p_environment_key text,p_revision text,p_summary text,p_artifact_digest text default null) returns public.cms_releases language plpgsql security definer set search_path=public as $$ declare v_env public.cms_environments;v_release public.cms_releases;
begin if not public.cms_can('publish') then raise exception 'permission_denied';end if;select * into v_env from public.cms_environments where environment_key=p_environment_key;if v_env.id is null then raise exception 'environment_not_configured';end if;if p_revision!~'^[A-Za-z0-9._/\-]{7,160}$' or length(trim(p_summary))<3 then raise exception 'invalid_release_request';end if;
 insert into public.cms_releases(environment_id,revision,summary,artifact_digest,requested_by,status) values(v_env.id,p_revision,trim(p_summary),p_artifact_digest,auth.uid(),case when v_env.is_protected then 'requested' else 'approved' end) returning * into v_release;
 insert into public.cms_audit_logs(actor_id,action,resource_type,resource_id,metadata) values(auth.uid(),'release_requested','release',v_release.id::text,jsonb_build_object('environment',p_environment_key,'revision',p_revision));return v_release;end $$;

create or replace function public.cms_approve_release(p_release_id uuid) returns public.cms_releases language plpgsql security definer set search_path=public as $$ declare v_release public.cms_releases;
begin if not public.cms_can('publish') then raise exception 'permission_denied';end if;update public.cms_releases set status='approved',approved_by=auth.uid(),approved_at=now() where id=p_release_id and status='requested' and requested_by<>auth.uid() returning * into v_release;if v_release.id is null then raise exception 'self_approval_or_invalid_status';end if;insert into public.cms_audit_logs(actor_id,action,resource_type,resource_id,metadata) values(auth.uid(),'release_approved','release',p_release_id::text,'{}'::jsonb);return v_release;end $$;

create or replace function public.cms_record_release_status(p_release_id uuid,p_status text,p_provider_run_url text default null,p_error_message text default '') returns public.cms_releases language plpgsql security definer set search_path=public as $$ declare v_release public.cms_releases;v_role text:=coalesce(current_setting('request.jwt.claim.role',true),'');begin
 if v_role<>'service_role' then raise exception 'service_role_required';end if;if p_status not in('queued','deploying','succeeded','failed','cancelled') then raise exception 'invalid_release_status';end if;
 update public.cms_releases set status=p_status,provider_run_url=coalesce(p_provider_run_url,provider_run_url),error_message=left(coalesce(p_error_message,''),1000),started_at=case when p_status='deploying' then coalesce(started_at,now()) else started_at end,finished_at=case when p_status in('succeeded','failed','cancelled') then now() else finished_at end where id=p_release_id and status not in('succeeded','failed','cancelled') returning * into v_release;if v_release.id is null then raise exception 'release_not_mutable';end if;
 if p_status='succeeded' then update public.cms_environments set last_deployed_revision=v_release.revision,last_deployed_at=now(),updated_at=now() where id=v_release.environment_id;end if;return v_release;end $$;

revoke execute on function public.cms_request_release(text,text,text,text),public.cms_approve_release(uuid),public.cms_record_release_status(uuid,text,text,text) from public,anon;
grant execute on function public.cms_request_release(text,text,text,text),public.cms_approve_release(uuid) to authenticated;grant execute on function public.cms_record_release_status(uuid,text,text,text) to service_role;
