-- Rebuildable baseline for the CMS tables that predate the governance migrations.
create extension if not exists pgcrypto;
create table if not exists public.cms_admins(user_id uuid primary key references auth.users(id) on delete cascade,email text not null unique,created_at timestamptz not null default now());
create table if not exists public.cms_pages(id uuid primary key default gen_random_uuid(),page_key text not null unique,page_type text not null check(page_type in('home','about','product')),route text not null unique,title text not null,source_locale text not null default'en'check(source_locale in('en','zh')),draft_content jsonb not null default'{}',translations jsonb not null default'{}',translation_status jsonb not null default'{}',published_content jsonb not null default'{}',status text not null default'draft'check(status in('draft','published')),updated_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz);
create table if not exists public.cms_revisions(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.cms_pages(id) on delete cascade,revision_no bigint generated always as identity,action text not null check(action in('draft_saved','published','restored')),snapshot jsonb not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),unique(page_id,revision_no));
create table if not exists public.cms_assets(id uuid primary key default gen_random_uuid(),storage_path text not null unique,public_url text not null,original_name text not null,mime_type text not null,byte_size bigint not null check(byte_size>=0),width integer,height integer,alt_text text not null default'',uploaded_by uuid not null references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.cms_preview_links(id uuid primary key default gen_random_uuid(),page_id uuid not null references public.cms_pages(id) on delete cascade,token_hash text not null unique,expires_at timestamptz not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),revoked_at timestamptz);
create index if not exists cms_revisions_page_created_idx on public.cms_revisions(page_id,created_at desc);create index if not exists cms_preview_links_page_expiry_idx on public.cms_preview_links(page_id,expires_at desc);
alter table public.cms_admins enable row level security;alter table public.cms_pages enable row level security;alter table public.cms_revisions enable row level security;alter table public.cms_assets enable row level security;alter table public.cms_preview_links enable row level security;
grant usage on schema public to authenticated;grant select on public.cms_admins to authenticated;grant select,insert,update,delete on public.cms_pages to authenticated;grant select,insert on public.cms_revisions to authenticated;grant select,insert,update,delete on public.cms_assets,public.cms_preview_links to authenticated;grant usage,select on sequence public.cms_revisions_revision_no_seq to authenticated;
drop policy if exists "CMS admin reads own profile" on public.cms_admins;create policy "CMS admin reads own profile" on public.cms_admins for select to authenticated using(auth.uid()=user_id);
drop policy if exists "CMS admin manages pages" on public.cms_pages;create policy "CMS admin manages pages" on public.cms_pages for all to authenticated using(exists(select 1 from public.cms_admins a where a.user_id=auth.uid()))with check(updated_by=auth.uid()and exists(select 1 from public.cms_admins a where a.user_id=auth.uid()));
drop policy if exists "CMS admin reads revisions" on public.cms_revisions;create policy "CMS admin reads revisions" on public.cms_revisions for select to authenticated using(exists(select 1 from public.cms_admins a where a.user_id=auth.uid()));
drop policy if exists "CMS admin creates revisions" on public.cms_revisions;create policy "CMS admin creates revisions" on public.cms_revisions for insert to authenticated with check(created_by=auth.uid()and exists(select 1 from public.cms_admins a where a.user_id=auth.uid()));
drop policy if exists "CMS admin manages assets" on public.cms_assets;create policy "CMS admin manages assets" on public.cms_assets for all to authenticated using(exists(select 1 from public.cms_admins a where a.user_id=auth.uid()))with check(uploaded_by=auth.uid()and exists(select 1 from public.cms_admins a where a.user_id=auth.uid()));
drop policy if exists "CMS admin manages preview links" on public.cms_preview_links;create policy "CMS admin manages preview links" on public.cms_preview_links for all to authenticated using(exists(select 1 from public.cms_admins a where a.user_id=auth.uid()))with check(created_by=auth.uid()and exists(select 1 from public.cms_admins a where a.user_id=auth.uid()));
insert into storage.buckets(id,name,public)values('website-assets','website-assets',true)on conflict(id)do nothing;
