-- Privacy-preserving rule-based recommendations.
create table if not exists public.cms_recommendation_rules(id uuid primary key default gen_random_uuid(),name text not null,priority integer not null default 100,criteria jsonb not null default '{}'::jsonb,draft_content jsonb not null,published_content jsonb,status text not null default 'draft' check(status in('draft','in_review','published','disabled')),version bigint not null default 1,submitted_by uuid references auth.users(id),published_by uuid references auth.users(id),updated_by uuid not null references auth.users(id),updated_at timestamptz not null default now(),published_at timestamptz);
alter table public.cms_recommendation_rules enable row level security; grant select on public.cms_recommendation_rules to authenticated;
create policy "CMS reads recommendation rules" on public.cms_recommendation_rules for select to authenticated using(public.cms_can('read'));
create or replace function public.cms_validate_recommendation(p_criteria jsonb,p_content jsonb) returns void language plpgsql immutable as $$ begin
 if jsonb_typeof(p_criteria)<>'object' or jsonb_typeof(p_content)<>'object' then raise exception 'invalid_recommendation'; end if;
 if coalesce(p_content->>'title','')='' or coalesce(p_content->>'url','')!~'^/' then raise exception 'title_and_internal_url_required'; end if;
 if p_criteria?'route_prefix' and p_criteria->>'route_prefix'!~'^/' then raise exception 'invalid_route_prefix'; end if;
end $$;
create or replace function public.cms_save_recommendation(p_id uuid,p_name text,p_priority integer,p_criteria jsonb,p_content jsonb,p_expected_version bigint default null) returns public.cms_recommendation_rules language plpgsql security definer set search_path=public as $$ declare v public.cms_recommendation_rules; begin
 if not public.cms_can('edit') then raise exception 'permission_denied'; end if; perform public.cms_validate_recommendation(p_criteria,p_content);
 if p_id is null then insert into public.cms_recommendation_rules(name,priority,criteria,draft_content,updated_by) values(trim(p_name),p_priority,p_criteria,p_content,auth.uid()) returning * into v;
 else update public.cms_recommendation_rules set name=trim(p_name),priority=p_priority,criteria=p_criteria,draft_content=p_content,status='draft',version=version+1,updated_by=auth.uid(),updated_at=now() where id=p_id and version=p_expected_version returning * into v; if not found then raise exception 'version_conflict'; end if; end if;
 insert into public.cms_audit_logs(actor_id,action,resource_type,resource_id,metadata) values(auth.uid(),'recommendation_saved','recommendation',v.id::text,jsonb_build_object('version',v.version));return v;
end $$;
create or replace function public.cms_submit_recommendation(p_id uuid,p_expected_version bigint) returns void language plpgsql security definer set search_path=public as $$ begin if not public.cms_can('submit') then raise exception 'permission_denied'; end if; update public.cms_recommendation_rules set status='in_review',submitted_by=auth.uid(),updated_at=now() where id=p_id and version=p_expected_version and status='draft';if not found then raise exception 'version_conflict_or_invalid_status';end if;end $$;
create or replace function public.cms_publish_recommendation(p_id uuid,p_expected_version bigint) returns void language plpgsql security definer set search_path=public as $$ declare v_submitter uuid;begin if not public.cms_can('publish') then raise exception 'permission_denied';end if;select submitted_by into v_submitter from public.cms_recommendation_rules where id=p_id and version=p_expected_version and status='in_review' for update;if not found or (v_submitter=auth.uid() and public.cms_current_role()<>'super_admin') then raise exception 'self_approval_or_invalid_status';end if;update public.cms_recommendation_rules set published_content=draft_content,status='published',published_by=auth.uid(),published_at=now(),updated_at=now() where id=p_id;insert into public.cms_audit_logs(actor_id,action,resource_type,resource_id,metadata) values(auth.uid(),'recommendation_published','recommendation',p_id::text,jsonb_build_object('version',p_expected_version));end $$;
create or replace view public.cms_published_recommendations with(security_invoker=false) as select id,name,priority,criteria,published_content,published_at from public.cms_recommendation_rules where status='published' and published_content is not null order by priority,id;
revoke all on public.cms_published_recommendations from public;grant select on public.cms_published_recommendations to anon,authenticated;
revoke execute on function public.cms_save_recommendation(uuid,text,integer,jsonb,jsonb,bigint),public.cms_submit_recommendation(uuid,bigint),public.cms_publish_recommendation(uuid,bigint) from public,anon;grant execute on function public.cms_save_recommendation(uuid,text,integer,jsonb,jsonb,bigint),public.cms_submit_recommendation(uuid,bigint),public.cms_publish_recommendation(uuid,bigint) to authenticated;
